/**
 * Event Types
 *
 * Re-exports the shared event type constants and provides a mapping
 * from each event type to its logical category so consumers can
 * subscribe at the category level.
 *
 * @module server/events/event-types
 */

import { EVENT_TYPES } from '@signalforge/shared/constants/event-types';

export { EVENT_TYPES };

export const EVENT_CATEGORY_MAP = Object.freeze({
  SIGNAL: [
    EVENT_TYPES.MESSAGE_RECEIVED,
    EVENT_TYPES.MESSAGE_CLASSIFIED,
    EVENT_TYPES.SIGNAL_DETECTED,
    EVENT_TYPES.SIGNAL_ANALYSIS_REQUESTED,
    EVENT_TYPES.SIGNAL_ANALYZED,
    EVENT_TYPES.SIGNAL_UPDATED,
    EVENT_TYPES.SIGNAL_DELETED,
    EVENT_TYPES.SIGNAL_VALIDATED,
    EVENT_TYPES.SIGNAL_VALIDATION_FAILED,
    EVENT_TYPES.PROVIDER_DNA_LEARNED,
    EVENT_TYPES.PROVIDER_DNA_UPDATED,
    EVENT_TYPES.SIGNAL_DUPLICATE_DETECTED,
    EVENT_TYPES.SIGNAL_CONFLICT_DETECTED,
    EVENT_TYPES.CONSENSUS_REACHED,
    EVENT_TYPES.CONSENSUS_FAILED,
    EVENT_TYPES.SIGNAL_FANOUT_REQUESTED,
    EVENT_TYPES.SIGNAL_FANOUT_COMPLETED,
  ],
  TRADING: [
    EVENT_TYPES.RISK_CHECK_REQUESTED,
    EVENT_TYPES.RISK_APPROVED,
    EVENT_TYPES.RISK_REJECTED,
    EVENT_TYPES.RISK_LIMIT_HIT,
    EVENT_TYPES.AUTOMATION_RULE_TRIGGERED,
    EVENT_TYPES.EXECUTION_REQUESTED,
    EVENT_TYPES.EXECUTION_ACCEPTED,
    EVENT_TYPES.EXECUTION_REJECTED,
    EVENT_TYPES.EXECUTION_FAILED,
    EVENT_TYPES.EXECUTION_RETRY,
    EVENT_TYPES.TRADE_EXECUTED,
    EVENT_TYPES.TRADE_OPENED,
    EVENT_TYPES.TRADE_UPDATED,
    EVENT_TYPES.TRADE_CLOSED,
    EVENT_TYPES.TRADE_ARCHIVED,
    EVENT_TYPES.TRADE_SHADOW_CREATED,
  ],
  KYC: [
    EVENT_TYPES.KYC_SUBMITTED,
    EVENT_TYPES.KYC_APPROVED,
    EVENT_TYPES.KYC_REJECTED,
    EVENT_TYPES.KYC_EXPIRED,
    EVENT_TYPES.KYC_RESUBMIT_REQUESTED,
  ],
  BILLING: [
    EVENT_TYPES.SUBSCRIPTION_CREATED,
    EVENT_TYPES.SUBSCRIPTION_ACTIVATED,
    EVENT_TYPES.SUBSCRIPTION_RENEWED,
    EVENT_TYPES.SUBSCRIPTION_EXPIRED,
    EVENT_TYPES.SUBSCRIPTION_CANCELLED,
    EVENT_TYPES.SUBSCRIPTION_PAST_DUE,
    EVENT_TYPES.PAYMENT_INITIATED,
    EVENT_TYPES.PAYMENT_COMPLETED,
    EVENT_TYPES.PAYMENT_FAILED,
    EVENT_TYPES.PAYMENT_REFUNDED,
  ],
  REFERRAL: [
    EVENT_TYPES.REFERRAL_RELATIONSHIP_CREATED,
    EVENT_TYPES.REFERRAL_REWARD_CALCULATED,
    EVENT_TYPES.REFERRAL_REWARD_APPROVED,
    EVENT_TYPES.REFERRAL_REWARD_SETTLED,
    EVENT_TYPES.REFERRAL_SETTLEMENT_STARTED,
    EVENT_TYPES.REFERRAL_SETTLEMENT_COMPLETED,
  ],
  SOLANA: [
    EVENT_TYPES.SOLANA_WALLET_CONNECTED,
    EVENT_TYPES.SOLANA_WALLET_DISCONNECTED,
    EVENT_TYPES.SOLANA_ATTESTATION_ANCHORED,
    EVENT_TYPES.SOLANA_PROVENANCE_ANCHORED,
    EVENT_TYPES.SOLANA_TRANSACTION_CONFIRMED,
    EVENT_TYPES.SOLANA_TRANSACTION_FAILED,
    EVENT_TYPES.SOLANA_PAYMENT_CONFIRMED,
  ],
});

export function getCategoryForEvent(eventType) {
  for (const [category, events] of Object.entries(EVENT_CATEGORY_MAP)) {
    if (events.includes(eventType)) {
      return category;
    }
  }
  return 'UNCATEGORIZED';
}

export function getEventsForCategory(category) {
  return EVENT_CATEGORY_MAP[category] || [];
}

export const EVENT_CATEGORIES = Object.freeze(Object.keys(EVENT_CATEGORY_MAP));