/**
 * IB Revenue Service
 *
 * Tracks Introducing Broker revenue generated by referred accounts.
 * Revenue entries are created by the platform when a broker confirms
 * IB rebates and are aggregated here for partner dashboards and
 * withdrawals.
 *
 * @module server/modules/ib/revenue/ib-revenue.service
 */

import { AppError } from '../../../lib/errors/app-error';
import { ERROR_CODES } from '../../../lib/errors/error-codes';
import { logger } from '../../../lib/logger';
import { publishEvent } from '../../../events/event-publisher';
import { EVENT_TYPES } from '@signalforge/shared/constants/event-types';
import { normalizePagination, buildPaginationMeta } from '@signalforge/shared/utils/pagination.util';
import { IB_TIER_RATES } from '../ib.constants';
import * as repository from './ib-revenue.repository';

function getRateForTier(tier) {
  return IB_TIER_RATES[tier] || IB_TIER_RATES.STANDARD;
}

export async function recordRevenue({
  partnerUserId,
  referralId,
  baseAmount,
  tier = 'STANDARD',
  currency = 'USD',
  description,
}) {
  if (!partnerUserId || baseAmount === undefined) {
    throw new AppError('partnerUserId and baseAmount are required', ERROR_CODES.VALIDATION_FAILED, 400);
  }

  const base = Number(baseAmount);

  if (!Number.isFinite(base) || base <= 0) {
    throw new AppError('baseAmount must be a positive number', ERROR_CODES.VALIDATION_FAILED, 400);
  }

  const rate = getRateForTier(tier);
  const amount = Number((base * rate).toFixed(8));

  const entry = await repository.insertRevenueEntry({
    partnerUserId,
    referralId: referralId || null,
    amount,
    currency,
    status: 'PENDING',
    description: description || null,
  });

  await publishEvent({
    eventType: EVENT_TYPES.IB_COMMISSION_CALCULATED,
    source: 'ib-revenue.service',
    actorId: partnerUserId,
    payload: {
      revenueEntryId: entry.id,
      partnerUserId,
      referralId: referralId || null,
      baseAmount: base,
      rate,
      tier,
      amount,
      currency,
    },
  }).catch((err) => logger.warn({ err }, 'Failed to publish IB revenue event'));

  logger.info(
    { partnerUserId, revenueEntryId: entry.id, amount },
    'IB revenue entry recorded',
  );

  return {
    revenueEntryId: entry.id,
    partnerUserId,
    referralId: referralId || null,
    baseAmount: base,
    rate,
    tier,
    amount,
    currency,
    status: entry.status,
    createdAt: entry.created_at,
  };
}

export async function approveRevenue({ revenueEntryId, reviewerId }) {
  if (!revenueEntryId) {
    throw new AppError('revenueEntryId is required', ERROR_CODES.VALIDATION_FAILED, 400);
  }

  const updated = await repository.updateStatus({
    revenueEntryId,
    status: 'APPROVED',
  });

  if (!updated) {
    throw new AppError('Revenue entry not found', ERROR_CODES.NOT_FOUND, 404);
  }

  logger.info({ revenueEntryId, reviewerId }, 'IB revenue entry approved');

  return { approved: true };
}

export async function markRevenuePaid({ revenueEntryId }) {
  if (!revenueEntryId) {
    throw new AppError('revenueEntryId is required', ERROR_CODES.VALIDATION_FAILED, 400);
  }

  const updated = await repository.markPaid({ revenueEntryId });

  if (!updated) {
    throw new AppError('Revenue entry not found or not in APPROVED status', ERROR_CODES.NOT_FOUND, 404);
  }

  return { paid: true };
}

export async function rejectRevenue({ revenueEntryId, reason }) {
  if (!revenueEntryId) {
    throw new AppError('revenueEntryId is required', ERROR_CODES.VALIDATION_FAILED, 400);
  }

  const updated = await repository.updateStatus({
    revenueEntryId,
    status: 'REJECTED',
    rejectionReason: reason || null,
  });

  if (!updated) {
    throw new AppError('Revenue entry not found', ERROR_CODES.NOT_FOUND, 404);
  }

  return { rejected: true };
}

export async function getRevenueSummary({ userId, from, to }) {
  if (!userId) {
    throw new AppError('userId is required', ERROR_CODES.VALIDATION_FAILED, 400);
  }

  const aggregate = await repository.aggregateByPartner({ partnerUserId: userId, from, to });

  return {
    pendingAmount: Number(aggregate.pending || 0),
    approvedAmount: Number(aggregate.approved || 0),
    paidAmount: Number(aggregate.paid || 0),
    rejectedAmount: Number(aggregate.rejected || 0),
    totalCount: aggregate.total_count || 0,
    from: from || null,
    to: to || null,
  };
}

export async function listRevenueEntries({ userId, filters = {}, pagination = {} }) {
  if (!userId) {
    throw new AppError('userId is required', ERROR_CODES.VALIDATION_FAILED, 400);
  }

  const { page, limit, offset } = normalizePagination(pagination);

  const result = await repository.listRevenueEntries({
    partnerUserId: userId,
    filters,
    limit,
    offset,
  });

  return {
    items: result.items.map((row) => ({
      revenueEntryId: row.id,
      referralId: row.referral_id,
      amount: Number(row.amount),
      currency: row.currency,
      status: row.status,
      description: row.description,
      createdAt: row.created_at,
      updatedAt: row.updated_at,
    })),
    meta: buildPaginationMeta({ page, limit, total: result.total }),
  };
}

export async function listAllPending() {
  return repository.listByStatus({ status: 'PENDING' });
}

export const ibRevenueService = {
  recordRevenue,
  approveRevenue,
  markRevenuePaid,
  rejectRevenue,
  getRevenueSummary,
  listRevenueEntries,
  listAllPending,
};