/**
 * Event Types
 *
 * Defines the platform-wide events published and subscribed to via the
 * SignalForge Event Bus. Services communicate asynchronously through
 * these events to remain loosely coupled.
 *
 * @module @signalforge/shared/constants/event-types
 */

export const EVENT_TYPES = Object.freeze({
  // Signal pipeline
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_CLASSIFIED: 'MESSAGE_CLASSIFIED',
  SIGNAL_DETECTED: 'SIGNAL_DETECTED',
  SIGNAL_ANALYSIS_REQUESTED: 'SIGNAL_ANALYSIS_REQUESTED',
  SIGNAL_ANALYZED: 'SIGNAL_ANALYZED',
  SIGNAL_UPDATED: 'SIGNAL_UPDATED',
  SIGNAL_DELETED: 'SIGNAL_DELETED',
  SIGNAL_VALIDATED: 'SIGNAL_VALIDATED',
  SIGNAL_VALIDATION_FAILED: 'SIGNAL_VALIDATION_FAILED',
  PROVIDER_DNA_LEARNED: 'PROVIDER_DNA_LEARNED',
  PROVIDER_DNA_UPDATED: 'PROVIDER_DNA_UPDATED',
  SIGNAL_DUPLICATE_DETECTED: 'SIGNAL_DUPLICATE_DETECTED',
  SIGNAL_CONFLICT_DETECTED: 'SIGNAL_CONFLICT_DETECTED',
  CONSENSUS_REACHED: 'CONSENSUS_REACHED',
  CONSENSUS_FAILED: 'CONSENSUS_FAILED',
  SIGNAL_FANOUT_REQUESTED: 'SIGNAL_FANOUT_REQUESTED',
  SIGNAL_FANOUT_COMPLETED: 'SIGNAL_FANOUT_COMPLETED',

  // Risk
  RISK_CHECK_REQUESTED: 'RISK_CHECK_REQUESTED',
  RISK_APPROVED: 'RISK_APPROVED',
  RISK_REJECTED: 'RISK_REJECTED',
  RISK_LIMIT_HIT: 'RISK_LIMIT_HIT',

  // Automation
  AUTOMATION_RULE_TRIGGERED: 'AUTOMATION_RULE_TRIGGERED',
  AUTOMATION_RULE_CREATED: 'AUTOMATION_RULE_CREATED',
  AUTOMATION_RULE_UPDATED: 'AUTOMATION_RULE_UPDATED',

  // Execution
  EXECUTION_REQUESTED: 'EXECUTION_REQUESTED',
  EXECUTION_ACCEPTED: 'EXECUTION_ACCEPTED',
  EXECUTION_REJECTED: 'EXECUTION_REJECTED',
  EXECUTION_FAILED: 'EXECUTION_FAILED',
  EXECUTION_RETRY: 'EXECUTION_RETRY',
  TRADE_EXECUTED: 'TRADE_EXECUTED',

  // Trade lifecycle
  TRADE_OPENED: 'TRADE_OPENED',
  TRADE_UPDATED: 'TRADE_UPDATED',
  TRADE_CLOSED: 'TRADE_CLOSED',
  TRADE_ARCHIVED: 'TRADE_ARCHIVED',
  TRADE_SHADOW_CREATED: 'TRADE_SHADOW_CREATED',

  // Broker
  BROKER_ACCOUNT_CONNECTED: 'BROKER_ACCOUNT_CONNECTED',
  BROKER_ACCOUNT_DISCONNECTED: 'BROKER_ACCOUNT_DISCONNECTED',
  BROKER_ACCOUNT_SYNCED: 'BROKER_ACCOUNT_SYNCED',
  BROKER_ORDER_REJECTED: 'BROKER_ORDER_REJECTED',

  // Users
  USER_REGISTERED: 'USER_REGISTERED',
  USER_VERIFIED: 'USER_VERIFIED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',

  // KYC
  KYC_SUBMITTED: 'KYC_SUBMITTED',
  KYC_APPROVED: 'KYC_APPROVED',
  KYC_REJECTED: 'KYC_REJECTED',
  KYC_EXPIRED: 'KYC_EXPIRED',
  KYC_RESUBMIT_REQUESTED: 'KYC_RESUBMIT_REQUESTED',

  // Subscriptions
  SUBSCRIPTION_CREATED: 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_RENEWED: 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_PAST_DUE: 'SUBSCRIPTION_PAST_DUE',

  // Payments
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  SOLANA_PAYMENT_CONFIRMED: 'SOLANA_PAYMENT_CONFIRMED',

  // Wallet and ledger
  WALLET_CREDITED: 'WALLET_CREDITED',
  WALLET_DEBITED: 'WALLET_DEBITED',
  LEDGER_ENTRY_CREATED: 'LEDGER_ENTRY_CREATED',

  // Withdrawals
  WITHDRAWAL_REQUESTED: 'WITHDRAWAL_REQUESTED',
  WITHDRAWAL_APPROVED: 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',
  WITHDRAWAL_COMPLETED: 'WITHDRAWAL_COMPLETED',
  WITHDRAWAL_FAILED: 'WITHDRAWAL_FAILED',

  // Referrals
  REFERRAL_RELATIONSHIP_CREATED: 'REFERRAL_RELATIONSHIP_CREATED',
  REFERRAL_REWARD_CALCULATED: 'REFERRAL_REWARD_CALCULATED',
  REFERRAL_REWARD_APPROVED: 'REFERRAL_REWARD_APPROVED',
  REFERRAL_REWARD_SETTLED: 'REFERRAL_REWARD_SETTLED',
  REFERRAL_SETTLEMENT_STARTED: 'REFERRAL_SETTLEMENT_STARTED',
  REFERRAL_SETTLEMENT_COMPLETED: 'REFERRAL_SETTLEMENT_COMPLETED',

  // Providers
  PROVIDER_REGISTERED: 'PROVIDER_REGISTERED',
  PROVIDER_APPROVED: 'PROVIDER_APPROVED',
  PROVIDER_SUSPENDED: 'PROVIDER_SUSPENDED',
  PROVIDER_CERTIFIED: 'PROVIDER_CERTIFIED',

  // Marketplace
  MARKETPLACE_LISTING_CREATED: 'MARKETPLACE_LISTING_CREATED',
  MARKETPLACE_LISTING_UPDATED: 'MARKETPLACE_LISTING_UPDATED',
  MARKETPLACE_REVIEW_ADDED: 'MARKETPLACE_REVIEW_ADDED',
  MARKETPLACE_REVIEW_UPDATED: 'MARKETPLACE_REVIEW_UPDATED',

  // Affiliate and IB
  AFFILIATE_COMMISSION_CALCULATED: 'AFFILIATE_COMMISSION_CALCULATED',
  IB_COMMISSION_CALCULATED: 'IB_COMMISSION_CALCULATED',

  // Notifications
  NOTIFICATION_QUEUED: 'NOTIFICATION_QUEUED',
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',

  // Security
  SECURITY_ALERT: 'SECURITY_ALERT',
  API_KEY_CREATED: 'API_KEY_CREATED',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  SUSPICIOUS_ACTIVITY_DETECTED: 'SUSPICIOUS_ACTIVITY_DETECTED',

  // Audit
  AUDIT_LOG_CREATED: 'AUDIT_LOG_CREATED',

  // Solana
  SOLANA_WALLET_CONNECTED: 'SOLANA_WALLET_CONNECTED',
  SOLANA_WALLET_DISCONNECTED: 'SOLANA_WALLET_DISCONNECTED',
  SOLANA_ATTESTATION_ANCHORED: 'SOLANA_ATTESTATION_ANCHORED',
  SOLANA_PROVENANCE_ANCHORED: 'SOLANA_PROVENANCE_ANCHORED',
  SOLANA_TRANSACTION_CONFIRMED: 'SOLANA_TRANSACTION_CONFIRMED',
  SOLANA_TRANSACTION_FAILED: 'SOLANA_TRANSACTION_FAILED',
});

export const EVENT_TYPE_VALUES = Object.freeze(Object.values(EVENT_TYPES));

export const EVENT_CATEGORIES = Object.freeze({
  SIGNAL: [
    EVENT_TYPES.MESSAGE_RECEIVED,
    EVENT_TYPES.MESSAGE_CLASSIFIED,
    EVENT_TYPES.SIGNAL_DETECTED,
    EVENT_TYPES.SIGNAL_ANALYSIS_REQUESTED,
    EVENT_TYPES.SIGNAL_ANALYZED,
    EVENT_TYPES.SIGNAL_UPDATED,
    EVENT_TYPES.SIGNAL_DELETED,
    EVENT_TYPES.SIGNAL_VALIDATED,
    EVENT_TYPES.SIGNAL_VALIDATION_FAILED,
    EVENT_TYPES.PROVIDER_DNA_LEARNED,
    EVENT_TYPES.PROVIDER_DNA_UPDATED,
    EVENT_TYPES.SIGNAL_DUPLICATE_DETECTED,
    EVENT_TYPES.SIGNAL_CONFLICT_DETECTED,
    EVENT_TYPES.CONSENSUS_REACHED,
    EVENT_TYPES.CONSENSUS_FAILED,
    EVENT_TYPES.SIGNAL_FANOUT_REQUESTED,
    EVENT_TYPES.SIGNAL_FANOUT_COMPLETED,
  ],
  TRADING: [
    EVENT_TYPES.RISK_CHECK_REQUESTED,
    EVENT_TYPES.RISK_APPROVED,
    EVENT_TYPES.RISK_REJECTED,
    EVENT_TYPES.AUTOMATION_RULE_TRIGGERED,
    EVENT_TYPES.EXECUTION_REQUESTED,
    EVENT_TYPES.EXECUTION_ACCEPTED,
    EVENT_TYPES.EXECUTION_REJECTED,
    EVENT_TYPES.EXECUTION_FAILED,
    EVENT_TYPES.EXECUTION_RETRY,
    EVENT_TYPES.TRADE_EXECUTED,
    EVENT_TYPES.TRADE_OPENED,
    EVENT_TYPES.TRADE_UPDATED,
    EVENT_TYPES.TRADE_CLOSED,
    EVENT_TYPES.TRADE_ARCHIVED,
    EVENT_TYPES.TRADE_SHADOW_CREATED,
  ],
  KYC: [
    EVENT_TYPES.KYC_SUBMITTED,
    EVENT_TYPES.KYC_APPROVED,
    EVENT_TYPES.KYC_REJECTED,
    EVENT_TYPES.KYC_EXPIRED,
    EVENT_TYPES.KYC_RESUBMIT_REQUESTED,
  ],
  BILLING: [
    EVENT_TYPES.SUBSCRIPTION_CREATED,
    EVENT_TYPES.SUBSCRIPTION_ACTIVATED,
    EVENT_TYPES.SUBSCRIPTION_RENEWED,
    EVENT_TYPES.SUBSCRIPTION_EXPIRED,
    EVENT_TYPES.SUBSCRIPTION_CANCELLED,
    EVENT_TYPES.SUBSCRIPTION_PAST_DUE,
    EVENT_TYPES.PAYMENT_INITIATED,
    EVENT_TYPES.PAYMENT_COMPLETED,
    EVENT_TYPES.PAYMENT_FAILED,
    EVENT_TYPES.PAYMENT_REFUNDED,
  ],
  REFERRAL: [
    EVENT_TYPES.REFERRAL_RELATIONSHIP_CREATED,
    EVENT_TYPES.REFERRAL_REWARD_CALCULATED,
    EVENT_TYPES.REFERRAL_REWARD_APPROVED,
    EVENT_TYPES.REFERRAL_REWARD_SETTLED,
    EVENT_TYPES.REFERRAL_SETTLEMENT_STARTED,
    EVENT_TYPES.REFERRAL_SETTLEMENT_COMPLETED,
  ],
  SOLANA: [
    EVENT_TYPES.SOLANA_WALLET_CONNECTED,
    EVENT_TYPES.SOLANA_WALLET_DISCONNECTED,
    EVENT_TYPES.SOLANA_ATTESTATION_ANCHORED,
    EVENT_TYPES.SOLANA_PROVENANCE_ANCHORED,
    EVENT_TYPES.SOLANA_TRANSACTION_CONFIRMED,
    EVENT_TYPES.SOLANA_TRANSACTION_FAILED,
    EVENT_TYPES.SOLANA_PAYMENT_CONFIRMED,
  ],
});

export function isValidEventType(type) {
  return EVENT_TYPE_VALUES.includes(type);
}