/**
 * Notification Types
 *
 * Defines the categories of notifications sent by the platform.
 *
 * @module @signalforge/shared/constants/notification-types
 */

export const NOTIFICATION_TYPES = Object.freeze({
  // Authentication
  WELCOME: 'WELCOME',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PHONE_VERIFICATION: 'PHONE_VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  TWO_FACTOR_ENABLED: 'TWO_FACTOR_ENABLED',
  TWO_FACTOR_DISABLED: 'TWO_FACTOR_DISABLED',
  NEW_DEVICE_LOGIN: 'NEW_DEVICE_LOGIN',
  SUSPICIOUS_LOGIN: 'SUSPICIOUS_LOGIN',

  // KYC
  KYC_SUBMITTED: 'KYC_SUBMITTED',
  KYC_UNDER_REVIEW: 'KYC_UNDER_REVIEW',
  KYC_APPROVED: 'KYC_APPROVED',
  KYC_REJECTED: 'KYC_REJECTED',
  KYC_RESUBMIT_REQUIRED: 'KYC_RESUBMIT_REQUIRED',
  KYC_EXPIRED: 'KYC_EXPIRED',

  // Signals
  SIGNAL_DETECTED: 'SIGNAL_DETECTED',
  SIGNAL_VALIDATED: 'SIGNAL_VALIDATED',
  SIGNAL_REJECTED: 'SIGNAL_REJECTED',
  SIGNAL_DUPLICATE: 'SIGNAL_DUPLICATE',
  SIGNAL_CONSENSUS: 'SIGNAL_CONSENSUS',

  // Trades
  TRADE_OPENED: 'TRADE_OPENED',
  TRADE_MODIFIED: 'TRADE_MODIFIED',
  TRADE_CLOSED: 'TRADE_CLOSED',
  STOP_LOSS_HIT: 'STOP_LOSS_HIT',
  TAKE_PROFIT_HIT: 'TAKE_PROFIT_HIT',
  BREAK_EVEN_SET: 'BREAK_EVEN_SET',
  TRAILING_STOP_APPLIED: 'TRAILING_STOP_APPLIED',
  PARTIAL_CLOSE_EXECUTED: 'PARTIAL_CLOSE_EXECUTED',
  TRADE_SHADOW_DIVERGENCE: 'TRADE_SHADOW_DIVERGENCE',

  // Risk and Automation
  RISK_LIMIT_HIT: 'RISK_LIMIT_HIT',
  DAILY_LOSS_LIMIT_REACHED: 'DAILY_LOSS_LIMIT_REACHED',
  DRAWDOWN_LIMIT_REACHED: 'DRAWDOWN_LIMIT_REACHED',
  EMERGENCY_STOP_TRIGGERED: 'EMERGENCY_STOP_TRIGGERED',
  AUTOMATION_RULE_TRIGGERED: 'AUTOMATION_RULE_TRIGGERED',

  // Brokers
  BROKER_CONNECTED: 'BROKER_CONNECTED',
  BROKER_DISCONNECTED: 'BROKER_DISCONNECTED',
  BROKER_CONNECTION_FAILED: 'BROKER_CONNECTION_FAILED',
  BROKER_SYNC_ISSUE: 'BROKER_SYNC_ISSUE',
  BROKER_REJECTED_ORDER: 'BROKER_REJECTED_ORDER',

  // Subscriptions
  SUBSCRIPTION_TRIAL_STARTED: 'SUBSCRIPTION_TRIAL_STARTED',
  SUBSCRIPTION_TRIAL_ENDING: 'SUBSCRIPTION_TRIAL_ENDING',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_RENEWED: 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_PAST_DUE: 'SUBSCRIPTION_PAST_DUE',
  SUBSCRIPTION_GRACE_PERIOD: 'SUBSCRIPTION_GRACE_PERIOD',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',

  // Payments
  PAYMENT_SUCCESSFUL: 'PAYMENT_SUCCESSFUL',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  SOLANA_PAYMENT_CONFIRMED: 'SOLANA_PAYMENT_CONFIRMED',

  // Referrals
  REFERRAL_JOINED: 'REFERRAL_JOINED',
  REFERRAL_REWARD_PENDING: 'REFERRAL_REWARD_PENDING',
  REFERRAL_REWARD_APPROVED: 'REFERRAL_REWARD_APPROVED',
  REFERRAL_REWARD_SETTLED: 'REFERRAL_REWARD_SETTLED',
  REFERRAL_REWARD_REJECTED: 'REFERRAL_REWARD_REJECTED',
  REFERRAL_UNDER_REVIEW: 'REFERRAL_UNDER_REVIEW',

  // Withdrawals
  WITHDRAWAL_REQUESTED: 'WITHDRAWAL_REQUESTED',
  WITHDRAWAL_APPROVED: 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',
  WITHDRAWAL_COMPLETED: 'WITHDRAWAL_COMPLETED',
  WITHDRAWAL_FAILED: 'WITHDRAWAL_FAILED',

  // Providers
  PROVIDER_APPROVED: 'PROVIDER_APPROVED',
  PROVIDER_SUSPENDED: 'PROVIDER_SUSPENDED',
  PROVIDER_CERTIFIED: 'PROVIDER_CERTIFIED',
  PROVIDER_DNA_UPDATED: 'PROVIDER_DNA_UPDATED',
  PROVIDER_NEW_SUBSCRIBER: 'PROVIDER_NEW_SUBSCRIBER',
  PROVIDER_SUBSCRIBER_LOST: 'PROVIDER_SUBSCRIBER_LOST',

  // Marketplace
  MARKETPLACE_REVIEW_RECEIVED: 'MARKETPLACE_REVIEW_RECEIVED',
  MARKETPLACE_REVIEW_REPLY: 'MARKETPLACE_REVIEW_REPLY',

  // Affiliate and IB
  AFFILIATE_COMMISSION_EARNED: 'AFFILIATE_COMMISSION_EARNED',
  IB_COMMISSION_EARNED: 'IB_COMMISSION_EARNED',

  // Security
  SECURITY_ALERT: 'SECURITY_ALERT',
  API_KEY_CREATED: 'API_KEY_CREATED',
  API_KEY_REVOKED: 'API_KEY_REVOKED',

  // Solana
  SOLANA_WALLET_CONNECTED: 'SOLANA_WALLET_CONNECTED',
  SOLANA_WALLET_DISCONNECTED: 'SOLANA_WALLET_DISCONNECTED',
  SOLANA_ATTESTATION_ANCHORED: 'SOLANA_ATTESTATION_ANCHORED',
  SOLANA_PROVENANCE_ANCHORED: 'SOLANA_PROVENANCE_ANCHORED',

  // System
  SYSTEM_MAINTENANCE: 'SYSTEM_MAINTENANCE',
  SYSTEM_ANNOUNCEMENT: 'SYSTEM_ANNOUNCEMENT',
  SYSTEM_INCIDENT: 'SYSTEM_INCIDENT',

  // Support
  SUPPORT_TICKET_CREATED: 'SUPPORT_TICKET_CREATED',
  SUPPORT_TICKET_REPLY: 'SUPPORT_TICKET_REPLY',
  SUPPORT_TICKET_RESOLVED: 'SUPPORT_TICKET_RESOLVED',
});

export const NOTIFICATION_TYPE_VALUES = Object.freeze(
  Object.values(NOTIFICATION_TYPES),
);

export const NOTIFICATION_PRIORITIES = Object.freeze({
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
});

export const NOTIFICATION_PRIORITY_VALUES = Object.freeze(
  Object.values(NOTIFICATION_PRIORITIES),
);

export const NOTIFICATION_CATEGORIES = Object.freeze({
  AUTH: 'AUTH',
  KYC: 'KYC',
  SIGNAL: 'SIGNAL',
  TRADE: 'TRADE',
  RISK: 'RISK',
  BROKER: 'BROKER',
  SUBSCRIPTION: 'SUBSCRIPTION',
  PAYMENT: 'PAYMENT',
  REFERRAL: 'REFERRAL',
  WITHDRAWAL: 'WITHDRAWAL',
  PROVIDER: 'PROVIDER',
  MARKETPLACE: 'MARKETPLACE',
  AFFILIATE: 'AFFILIATE',
  IB: 'IB',
  SECURITY: 'SECURITY',
  SOLANA: 'SOLANA',
  SYSTEM: 'SYSTEM',
  SUPPORT: 'SUPPORT',
});

export const NOTIFICATION_CATEGORY_VALUES = Object.freeze(
  Object.values(NOTIFICATION_CATEGORIES),
);

export function isValidNotificationType(type) {
  return NOTIFICATION_TYPE_VALUES.includes(type);
}

export function isValidNotificationCategory(category) {
  return NOTIFICATION_CATEGORY_VALUES.includes(category);
}

export function isValidNotificationPriority(priority) {
  return NOTIFICATION_PRIORITY_VALUES.includes(priority);
}