/**
 * API Endpoints
 *
 * Central index of every API endpoint path. Domain API modules import
 * from here so paths live in exactly one place.
 *
 * @module client/src/api/endpoints
 */

import { apiConfig } from '../config/api.config.js';

const base = apiConfig.endpoints;

export const endpoints = Object.freeze({
  auth: {
    register: `${base.auth}/register`,
    login: `${base.auth}/login`,
    logout: `${base.auth}/logout`,
    refresh: `${base.auth}/refresh`,
    me: `${base.auth}/me`,
    verifyEmail: `${base.auth}/verify-email`,
    resendEmail: `${base.auth}/verify-email/resend`,
    verifyPhone: `${base.auth}/verify-phone`,
    resendPhone: `${base.auth}/verify-phone/resend`,
    forgotPassword: `${base.auth}/forgot-password`,
    resetPassword: `${base.auth}/reset-password`,
    changePassword: `${base.auth}/change-password`,
    twoFactorSetup: `${base.auth}/2fa/setup`,
    twoFactorVerify: `${base.auth}/2fa/verify`,
    twoFactorDisable: `${base.auth}/2fa/disable`,
    sessionVerify: `${base.auth}/session/verify`,
  },
  users: {
    profile: `${base.users}/me`,
    updateProfile: `${base.users}/me`,
    preferences: `${base.users}/me/preferences`,
    sessions: `${base.users}/me/sessions`,
    revokeSession: (sessionId) => `${base.users}/me/sessions/${sessionId}`,
    devices: `${base.users}/me/devices`,
    deleteAccount: `${base.users}/me`,
    lookup: (userId) => `${base.users}/${userId}`,
  },
  rbac: {
    roles: `${base.rbac}/roles`,
    permissions: `${base.rbac}/permissions`,
    assignRole: `${base.rbac}/assign`,
    revokeRole: `${base.rbac}/revoke`,
  },
  kyc: {
    status: `${base.kyc}/status`,
    application: `${base.kyc}/application`,
    submitPersonalInfo: `${base.kyc}/personal-info`,
    documentTypes: `${base.kyc}/document-types`,
    uploadDocument: `${base.kyc}/documents`,
    uploadSelfie: `${base.kyc}/selfie`,
    submitApplication: `${base.kyc}/submit`,
    resubmit: `${base.kyc}/resubmit`,
    documents: `${base.kyc}/documents`,
    document: (documentId) => `${base.kyc}/documents/${documentId}`,
    verificationResult: `${base.kyc}/result`,
  },
  sources: {
    list: base.sources,
    create: base.sources,
    details: (sourceId) => `${base.sources}/${sourceId}`,
    update: (sourceId) => `${base.sources}/${sourceId}`,
    delete: (sourceId) => `${base.sources}/${sourceId}`,
    health: (sourceId) => `${base.sources}/${sourceId}/health`,
  },
  telegram: {
    status: `${base.telegram}/status`,
    initiate: `${base.telegram}/login/initiate`,
    completeLogin: `${base.telegram}/login/complete`,
    submitPassword: `${base.telegram}/login/password`,
    logout: `${base.telegram}/logout`,
    channels: `${base.telegram}/channels`,
    discoverChannels: `${base.telegram}/channels/discover`,
    optIn: `${base.telegram}/channels/opt-in`,
    optOut: `${base.telegram}/channels/opt-out`,
    listener: `${base.telegram}/listener`,
    startListening: `${base.telegram}/listener/start`,
    stopListening: `${base.telegram}/listener/stop`,
    health: `${base.telegram}/health`,
  },
  discord: {
    status: `${base.discord}/status`,
    authorize: `${base.discord}/oauth/authorize`,
    connect: `${base.discord}/oauth/connect`,
    disconnect: `${base.discord}/disconnect`,
    guilds: `${base.discord}/guilds`,
    channels: `${base.discord}/channels`,
    discoverChannels: (guildId) => `${base.discord}/guilds/${guildId}/channels`,
    optIn: `${base.discord}/channels/opt-in`,
    optOut: `${base.discord}/channels/opt-out`,
  },
  whatsapp: {
    status: `${base.whatsapp}/status`,
    subscribe: `${base.whatsapp}/subscribe`,
    unsubscribe: `${base.whatsapp}/unsubscribe`,
    groups: `${base.whatsapp}/groups`,
    optIn: `${base.whatsapp}/groups/opt-in`,
    optOut: `${base.whatsapp}/groups/opt-out`,
    verify: `${base.whatsapp}/verify`,
  },
  tradingview: {
    integrations: `${base.tradingview}/integrations`,
    create: `${base.tradingview}/integrations`,
    remove: (integrationId) => `${base.tradingview}/integrations/${integrationId}`,
    webhookUrl: (routeToken) => `${base.tradingview}/webhook/${routeToken}`,
  },
  email: {
    status: `${base.email}/status`,
    subscribe: `${base.email}/subscribe`,
    unsubscribe: `${base.email}/unsubscribe`,
    mailbox: `${base.email}/mailbox`,
    verify: `${base.email}/verify`,
  },
  restApi: {
    keys: `${base.restApi}/keys`,
    createKey: `${base.restApi}/keys`,
    revokeKey: (keyId) => `${base.restApi}/keys/${keyId}`,
    submitSignal: `${base.restApi}/signal`,
  },
  messages: {
    list: base.messages,
    details: (messageId) => `${base.messages}/${messageId}`,
    status: (messageId) => `${base.messages}/${messageId}/status`,
    fingerprint: (messageId) => `${base.messages}/${messageId}/fingerprint`,
    reprocess: (messageId) => `${base.messages}/${messageId}/reprocess`,
    delete: (messageId) => `${base.messages}/${messageId}`,
  },
  signals: {
    list: base.signals,
    live: `${base.signals}/live`,
    history: `${base.signals}/history`,
    details: (signalId) => `${base.signals}/${signalId}`,
    timeline: (signalId) => `${base.signals}/${signalId}/timeline`,
    confidence: (signalId) => `${base.signals}/${signalId}/confidence`,
    risk: (signalId) => `${base.signals}/${signalId}/risk`,
    provider: (providerId) => `${base.signals}/provider/${providerId}`,
    duplicates: `${base.signals}/duplicates`,
    consensus: `${base.signals}/consensus`,
    rejected: `${base.signals}/rejected`,
    replay: (signalId) => `${base.signals}/${signalId}/replay`,
  },
  ai: {
    overview: `${base.ai}/overview`,
    parse: `${base.ai}/parse`,
    interpretation: (signalId) => `${base.ai}/interpretation/${signalId}`,
    learningActivity: `${base.ai}/learning`,
    confidenceEngine: `${base.ai}/confidence`,
    riskIntelligence: `${base.ai}/risk`,
    multilingual: `${base.ai}/multilingual`,
    consensusEngine: `${base.ai}/consensus`,
    duplicateDetection: `${base.ai}/duplicates`,
    processingLogs: `${base.ai}/logs`,
    modelPerformance: `${base.ai}/models`,
    learningHistory: `${base.ai}/history`,
  },
  providerDna: {
    list: base.providerDna,
    profile: (providerId) => `${base.providerDna}/${providerId}`,
    language: (providerId) => `${base.providerDna}/${providerId}/language`,
    symbols: (providerId) => `${base.providerDna}/${providerId}/symbols`,
    abbreviations: (providerId) => `${base.providerDna}/${providerId}/abbreviations`,
    managementRules: (providerId) => `${base.providerDna}/${providerId}/management`,
    riskBehavior: (providerId) => `${base.providerDna}/${providerId}/risk`,
    patterns: (providerId) => `${base.providerDna}/${providerId}/patterns`,
    confidence: (providerId) => `${base.providerDna}/${providerId}/confidence`,
    versions: (providerId) => `${base.providerDna}/${providerId}/versions`,
    trainingMessages: (providerId) => `${base.providerDna}/${providerId}/training`,
    test: (providerId) => `${base.providerDna}/${providerId}/test`,
  },
  consensus: {
    overview: `${base.consensus}/overview`,
    bySymbol: (symbol) => `${base.consensus}/symbol/${symbol}`,
    history: `${base.consensus}/history`,
  },
  risk: {
    profile: `${base.risk}/profile`,
    checks: `${base.risk}/checks`,
    decisions: `${base.risk}/decisions`,
    events: `${base.risk}/events`,
    emergencyStop: `${base.risk}/emergency-stop`,
  },
  automation: {
    rules: `${base.automation}/rules`,
    createRule: `${base.automation}/rules`,
    rule: (ruleId) => `${base.automation}/rules/${ruleId}`,
    updateRule: (ruleId) => `${base.automation}/rules/${ruleId}`,
    deleteRule: (ruleId) => `${base.automation}/rules/${ruleId}`,
    testRule: (ruleId) => `${base.automation}/rules/${ruleId}/test`,
    providerRules: `${base.automation}/provider-rules`,
  },
  execution: {
    requests: `${base.execution}/requests`,
    history: `${base.execution}/history`,
    retry: (executionId) => `${base.execution}/requests/${executionId}/retry`,
    logs: `${base.execution}/logs`,
  },
  copyTrading: {
    subscriptions: `${base.copyTrading}/subscriptions`,
    subscribe: `${base.copyTrading}/subscribe`,
    unsubscribe: (subscriptionId) => `${base.copyTrading}/subscriptions/${subscriptionId}`,
    settings: `${base.copyTrading}/settings`,
    scaling: `${base.copyTrading}/scaling`,
    status: `${base.copyTrading}/status`,
  },
  brokers: {
    accounts: `${base.brokers}/accounts`,
    connect: `${base.brokers}/accounts`,
    account: (accountId) => `${base.brokers}/accounts/${accountId}`,
    update: (accountId) => `${base.brokers}/accounts/${accountId}`,
    disconnect: (accountId) => `${base.brokers}/accounts/${accountId}/disconnect`,
    sync: (accountId) => `${base.brokers}/accounts/${accountId}/sync`,
    balance: (accountId) => `${base.brokers}/accounts/${accountId}/balance`,
    snapshots: (accountId) => `${base.brokers}/accounts/${accountId}/snapshots`,
    logs: (accountId) => `${base.brokers}/accounts/${accountId}/logs`,
    platforms: `${base.brokers}/platforms`,
  },
  trades: {
    list: base.trades,
    openPositions: `${base.trades}/positions`,
    position: (positionId) => `${base.trades}/positions/${positionId}`,
    history: `${base.trades}/history`,
    trade: (tradeId) => `${base.trades}/${tradeId}`,
    timeline: (tradeId) => `${base.trades}/${tradeId}/timeline`,
    events: (tradeId) => `${base.trades}/${tradeId}/events`,
    pending: `${base.trades}/pending`,
    close: (tradeId) => `${base.trades}/${tradeId}/close`,
    modify: (tradeId) => `${base.trades}/${tradeId}/modify`,
    shadow: (tradeId) => `${base.trades}/${tradeId}/shadow`,
    replay: (tradeId) => `${base.trades}/${tradeId}/replay`,
  },
  analytics: {
    overview: `${base.analytics}/overview`,
    performance: `${base.analytics}/performance`,
    equityCurve: `${base.analytics}/equity-curve`,
    profit: `${base.analytics}/profit`,
    drawdown: `${base.analytics}/drawdown`,
    winRate: `${base.analytics}/win-rate`,
    riskReward: `${base.analytics}/risk-reward`,
    sharpe: `${base.analytics}/sharpe`,
    sortino: `${base.analytics}/sortino`,
    bestSymbols: `${base.analytics}/symbols/best`,
    worstSymbols: `${base.analytics}/symbols/worst`,
    latency: `${base.analytics}/execution-latency`,
    riskBehavior: `${base.analytics}/risk-behavior`,
    calendar: `${base.analytics}/calendar`,
    reports: `${base.analytics}/reports`,
    export: `${base.analytics}/export`,
  },
  performance: {
    summary: `${base.performance}/summary`,
    periods: `${base.performance}/periods`,
    metrics: `${base.performance}/metrics`,
    equitySnapshots: `${base.performance}/equity`,
  },
  subscriptions: {
    plans: `${base.subscriptions}/plans`,
    current: `${base.subscriptions}/me`,
    create: `${base.subscriptions}`,
    upgrade: `${base.subscriptions}/upgrade`,
    downgrade: `${base.subscriptions}/downgrade`,
    cancel: `${base.subscriptions}/cancel`,
    usage: `${base.subscriptions}/usage`,
  },
  payments: {
    list: `${base.payments}`,
    create: `${base.payments}`,
    payment: (paymentId) => `${base.payments}/${paymentId}`,
    refund: (paymentId) => `${base.payments}/${paymentId}/refund`,
    methods: `${base.payments}/methods`,
    invoices: `${base.payments}/invoices`,
    invoice: (invoiceId) => `${base.payments}/invoices/${invoiceId}`,
  },
  wallet: {
    overview: `${base.wallets}/me`,
    balance: `${base.wallets}/me/balance`,
    ledger: `${base.wallets}/me/ledger`,
    transactions: `${base.wallets}/me/transactions`,
    paymentAccounts: `${base.wallets}/me/payment-accounts`,
  },
  withdrawals: {
    list: `${base.withdrawals}`,
    create: `${base.withdrawals}`,
    withdrawal: (withdrawalId) => `${base.withdrawals}/${withdrawalId}`,
    cancel: (withdrawalId) => `${base.withdrawals}/${withdrawalId}/cancel`,
    status: (withdrawalId) => `${base.withdrawals}/${withdrawalId}/status`,
  },
  referrals: {
    code: `${base.referrals}/code`,
    dashboard: `${base.referrals}/dashboard`,
    network: `${base.referrals}/network`,
    referredUsers: `${base.referrals}/users`,
    performance: `${base.referrals}/performance`,
    earnings: `${base.referrals}/earnings`,
    pendingRewards: `${base.referrals}/rewards/pending`,
    availableRewards: `${base.referrals}/rewards/available`,
    wallet: `${base.referrals}/wallet`,
    rewardHistory: `${base.referrals}/rewards`,
    monthlySettlement: `${base.referrals}/settlements`,
    leaderboard: `${base.referrals}/leaderboard`,
  },
  providers: {
    list: `${base.providers}`,
    profile: (providerId) => `${base.providers}/${providerId}`,
    update: (providerId) => `${base.providers}/${providerId}`,
    subscribers: (providerId) => `${base.providers}/${providerId}/subscribers`,
    revenue: (providerId) => `${base.providers}/${providerId}/revenue`,
    performance: (providerId) => `${base.providers}/${providerId}/performance`,
    signals: (providerId) => `${base.providers}/${providerId}/signals`,
    reviews: (providerId) => `${base.providers}/${providerId}/reviews`,
    subscriptionPlans: (providerId) => `${base.providers}/${providerId}/plans`,
    subscribe: (providerId) => `${base.providers}/${providerId}/subscribe`,
    unsubscribe: (providerId) => `${base.providers}/${providerId}/unsubscribe`,
    my: `${base.providers}/me`,
    register: `${base.providers}/register`,
  },
  certification: {
    status: (providerId) => `${base.certification}/${providerId}/status`,
    importHistory: (providerId) => `${base.certification}/${providerId}/import`,
    dataset: (providerId) => `${base.certification}/${providerId}/dataset`,
    parsingAccuracy: (providerId) => `${base.certification}/${providerId}/parsing`,
    backtest: (providerId) => `${base.certification}/${providerId}/backtest`,
    performance: (providerId) => `${base.certification}/${providerId}/performance`,
    risk: (providerId) => `${base.certification}/${providerId}/risk`,
    consistency: (providerId) => `${base.certification}/${providerId}/consistency`,
    quality: (providerId) => `${base.certification}/${providerId}/quality`,
    result: (providerId) => `${base.certification}/${providerId}/result`,
    history: (providerId) => `${base.certification}/${providerId}/history`,
  },
  marketplace: {
    listings: `${base.marketplace}/listings`,
    listing: (listingId) => `${base.marketplace}/listings/${listingId}`,
    reviews: `${base.marketplace}/reviews`,
    review: (reviewId) => `${base.marketplace}/reviews/${reviewId}`,
    search: `${base.marketplace}/search`,
    categories: `${base.marketplace}/categories`,
    featured: `${base.marketplace}/featured`,
    top: `${base.marketplace}/top`,
    compare: `${base.marketplace}/compare`,
    consensus: `${base.marketplace}/consensus`,
  },
  traders: {
    list: `${base.traders}`,
    profile: (traderId) => `${base.traders}/${traderId}`,
    performance: (traderId) => `${base.traders}/${traderId}/performance`,
    risk: (traderId) => `${base.traders}/${traderId}/risk`,
    behavior: (traderId) => `${base.traders}/${traderId}/behavior`,
    intelligence: (traderId) => `${base.traders}/${traderId}/intelligence`,
    reviews: (traderId) => `${base.traders}/${traderId}/reviews`,
    style: (traderId) => `${base.traders}/${traderId}/style`,
    follow: (traderId) => `${base.traders}/${traderId}/follow`,
    unfollow: (traderId) => `${base.traders}/${traderId}/unfollow`,
    copySettings: `${base.traders}/copy-settings`,
    myFollowed: `${base.traders}/me/followed`,
    leaderboard: `${base.traders}/leaderboard`,
  },
  traderIntelligence: {
    overview: `${base.traderIntelligence}/overview`,
    consistency: (traderId) => `${base.traderIntelligence}/${traderId}/consistency`,
    averageRiskReward: (traderId) => `${base.traderIntelligence}/${traderId}/risk-reward`,
    holdingTime: (traderId) => `${base.traderIntelligence}/${traderId}/holding-time`,
    riskBehavior: (traderId) => `${base.traderIntelligence}/${traderId}/risk-behavior`,
    martingaleGrid: (traderId) => `${base.traderIntelligence}/${traderId}/martingale-grid`,
    newsExposure: (traderId) => `${base.traderIntelligence}/${traderId}/news-exposure`,
    recoveryTrading: (traderId) => `${base.traderIntelligence}/${traderId}/recovery`,
    styleClassification: (traderId) => `${base.traderIntelligence}/${traderId}/style`,
    behaviorTimeline: (traderId) => `${base.traderIntelligence}/${traderId}/timeline`,
  },
  affiliate: {
    dashboard: `${base.affiliate}/dashboard`,
    links: `${base.affiliate}/links`,
    createLink: `${base.affiliate}/links`,
    link: (linkId) => `${base.affiliate}/links/${linkId}`,
    referrals: `${base.affiliate}/referrals`,
    commissions: `${base.affiliate}/commissions`,
    summary: `${base.affiliate}/commissions/summary`,
    withdraw: `${base.affiliate}/withdrawals`,
    withdrawals: `${base.affiliate}/withdrawals`,
  },
  ib: {
    dashboard: `${base.ib}/dashboard`,
    links: `${base.ib}/links`,
    createLink: `${base.ib}/links`,
    link: (linkId) => `${base.ib}/links/${linkId}`,
    referrals: `${base.ib}/referrals`,
    revenue: `${base.ib}/revenue`,
    revenueEntries: `${base.ib}/revenue/entries`,
    commissions: `${base.ib}/commissions`,
  },
  whiteLabel: {
    projects: `${base.whiteLabel}/projects`,
    project: (projectId) => `${base.whiteLabel}/projects/${projectId}`,
    createProject: `${base.whiteLabel}/projects`,
    deleteProject: (projectId) => `${base.whiteLabel}/projects/${projectId}`,
    branding: (projectId) => `${base.whiteLabel}/projects/${projectId}/branding`,
    theme: (projectId) => `${base.whiteLabel}/projects/${projectId}/theme`,
    pricing: (projectId) => `${base.whiteLabel}/projects/${projectId}/pricing`,
    domains: (projectId) => `${base.whiteLabel}/projects/${projectId}/domains`,
    domain: (projectId, domainId) => `${base.whiteLabel}/projects/${projectId}/domains/${domainId}`,
    verifyDomain: (projectId, domainId) => `${base.whiteLabel}/projects/${projectId}/domains/${domainId}/verify`,
    analytics: (projectId) => `${base.whiteLabel}/projects/${projectId}/analytics`,
    users: (projectId) => `${base.whiteLabel}/projects/${projectId}/users`,
    revenue: (projectId) => `${base.whiteLabel}/projects/${projectId}/revenue`,
    settings: (projectId) => `${base.whiteLabel}/projects/${projectId}/settings`,
  },
  notifications: {
    list: `${base.notifications}`,
    unreadCount: `${base.notifications}/unread-count`,
    markRead: (notificationId) => `${base.notifications}/${notificationId}/read`,
    markAllRead: `${base.notifications}/read-all`,
    delete: (notificationId) => `${base.notifications}/${notificationId}`,
    preferences: `${base.notifications}/preferences`,
  },
  replay: {
    signals: (signalId) => `${base.replay}/signals/${signalId}`,
    trades: (tradeId) => `${base.replay}/trades/${tradeId}`,
    ai: (signalId) => `${base.replay}/signals/${signalId}/ai`,
    risk: (signalId) => `${base.replay}/signals/${signalId}/risk`,
    execution: (tradeId) => `${base.replay}/trades/${tradeId}/execution`,
    providerMessage: (providerId, externalMessageId) =>
      `${base.replay}/providers/${providerId}/messages/${externalMessageId}`,
    system: (correlationId) => `${base.replay}/system/${correlationId}`,
  },
  admin: {
    overview: `${base.admin}/overview`,
    actions: `${base.admin}/actions`,
    health: `${base.admin}/health`,
    users: `${base.admin}/users`,
    user: (userId) => `${base.admin}/users/${userId}`,
    suspendUser: (userId) => `${base.admin}/users/${userId}/suspend`,
    activateUser: (userId) => `${base.admin}/users/${userId}/activate`,
    deactivateUser: (userId) => `${base.admin}/users/${userId}/deactivate`,
    revokeSessions: (userId) => `${base.admin}/users/${userId}/revoke-sessions`,
    userStatusBreakdown: `${base.admin}/users/status-breakdown`,
    providers: `${base.admin}/providers`,
    provider: (providerId) => `${base.admin}/providers/${providerId}`,
    approveProvider: (providerId) => `${base.admin}/providers/${providerId}/approve`,
    suspendProvider: (providerId) => `${base.admin}/providers/${providerId}/suspend`,
    certifyProvider: (providerId) => `${base.admin}/providers/${providerId}/certify`,
    providerStatusBreakdown: `${base.admin}/providers/status-breakdown`,
    signals: `${base.admin}/signals`,
    signal: (signalId) => `${base.admin}/signals/${signalId}`,
    signalStatusBreakdown: `${base.admin}/signals/status-breakdown`,
    rejectedSignals: `${base.admin}/signals/rejected`,
    duplicateSignals: `${base.admin}/signals/duplicate`,
    trades: `${base.admin}/trades`,
    trade: (tradeId) => `${base.admin}/trades/${tradeId}`,
    forceCloseTrade: (tradeId) => `${base.admin}/trades/${tradeId}/force-close`,
    tradeStatusBreakdown: `${base.admin}/trades/status-breakdown`,
    brokers: `${base.admin}/brokers`,
    brokerAccount: (brokerAccountId) => `${base.admin}/brokers/${brokerAccountId}`,
    disconnectBroker: (brokerAccountId) => `${base.admin}/brokers/${brokerAccountId}/disconnect`,
    brokerStatusBreakdown: `${base.admin}/brokers/status-breakdown`,
    kyc: `${base.admin}/kyc`,
    kycApplication: (applicationId) => `${base.admin}/kyc/${applicationId}`,
    kycStatusBreakdown: `${base.admin}/kyc/status-breakdown`,
    marketplaceListings: `${base.admin}/marketplace/listings`,
    suspendListing: (listingId) => `${base.admin}/marketplace/listings/${listingId}/suspend`,
    removeListing: (listingId) => `${base.admin}/marketplace/listings/${listingId}`,
    marketplaceReviews: `${base.admin}/marketplace/reviews`,
    approveReview: (reviewId) => `${base.admin}/marketplace/reviews/${reviewId}/approve`,
    rejectReview: (reviewId) => `${base.admin}/marketplace/reviews/${reviewId}/reject`,
    removeReview: (reviewId) => `${base.admin}/marketplace/reviews/${reviewId}`,
    referralRewards: `${base.admin}/referrals/rewards`,
    referralReward: (rewardId) => `${base.admin}/referrals/rewards/${rewardId}`,
    approveReferral: (rewardId) => `${base.admin}/referrals/rewards/${rewardId}/approve`,
    rejectReferral: (rewardId) => `${base.admin}/referrals/rewards/${rewardId}/reject`,
    referralRelationships: `${base.admin}/referrals/relationships`,
    referralStatusBreakdown: `${base.admin}/referrals/rewards/status-breakdown`,
    subscriptions: `${base.admin}/subscriptions`,
    subscription: (subscriptionId) => `${base.admin}/subscriptions/${subscriptionId}`,
    cancelSubscription: (subscriptionId) => `${base.admin}/subscriptions/${subscriptionId}/cancel`,
    extendSubscription: (subscriptionId) => `${base.admin}/subscriptions/${subscriptionId}/extend`,
    reactivateSubscription: (subscriptionId) => `${base.admin}/subscriptions/${subscriptionId}/reactivate`,
    subscriptionStatusBreakdown: `${base.admin}/subscriptions/status-breakdown`,
    payments: `${base.admin}/payments`,
    payment: (paymentId) => `${base.admin}/payments/${paymentId}`,
    refundPayment: (paymentId) => `${base.admin}/payments/${paymentId}/refund`,
    paymentStatusBreakdown: `${base.admin}/payments/status-breakdown`,
    revenueByProvider: `${base.admin}/payments/revenue-by-provider`,
    withdrawals: `${base.admin}/withdrawals`,
    withdrawal: (withdrawalId) => `${base.admin}/withdrawals/${withdrawalId}`,
    approveWithdrawal: (withdrawalId) => `${base.admin}/withdrawals/${withdrawalId}/approve`,
    rejectWithdrawal: (withdrawalId) => `${base.admin}/withdrawals/${withdrawalId}/reject`,
    completeWithdrawal: (withdrawalId) => `${base.admin}/withdrawals/${withdrawalId}/complete`,
    withdrawalStatusBreakdown: `${base.admin}/withdrawals/status-breakdown`,
    affiliatePartners: `${base.admin}/affiliate/partners`,
    affiliatePartner: (partnerId) => `${base.admin}/affiliate/partners/${partnerId}`,
    suspendAffiliate: (partnerId) => `${base.admin}/affiliate/partners/${partnerId}/suspend`,
    activateAffiliate: (partnerId) => `${base.admin}/affiliate/partners/${partnerId}/activate`,
    affiliateTier: (partnerId) => `${base.admin}/affiliate/partners/${partnerId}/tier`,
    affiliateCommissions: `${base.admin}/affiliate/commissions`,
    affiliateStatusBreakdown: `${base.admin}/affiliate/partners/status-breakdown`,
    systemSettings: `${base.admin}/system/settings`,
    systemSetting: (key) => `${base.admin}/system/settings/${key}`,
    publicSettings: `${base.admin}/system/settings/public`,
    featureFlags: `${base.admin}/system/flags`,
    featureFlag: (flagName) => `${base.admin}/system/flags/${flagName}`,
    systemHealth: `${base.admin}/system/health`,
    systemHealthQuick: `${base.admin}/system/health/quick`,
    reportPlatform: `${base.admin}/reports/platform`,
    reportUserGrowth: `${base.admin}/reports/user-growth`,
    reportSignalActivity: `${base.admin}/reports/signal-activity`,
    reportTradeActivity: `${base.admin}/reports/trade-activity`,
    reportRevenue: `${base.admin}/reports/revenue`,
    reportReferrals: `${base.admin}/reports/referrals`,
    reportExport: `${base.admin}/reports/export`,
  },
  compliance: {
    dashboard: `${base.compliance}/dashboard`,
    slaBreaches: `${base.compliance}/sla-breaches`,
    kycQueue: `${base.compliance}/queue`,
    kycQueueStats: `${base.compliance}/queue/stats`,
    kycQueueAssignedToMe: `${base.compliance}/queue/assigned-to-me`,
    assignReviewer: (applicationId) => `${base.compliance}/queue/${applicationId}/assign`,
    releaseReviewer: (applicationId) => `${base.compliance}/queue/${applicationId}/release`,
    reviewApplication: (applicationId) => `${base.compliance}/review/${applicationId}`,
    approveApplication: (applicationId) => `${base.compliance}/review/${applicationId}/approve`,
    rejectApplication: (applicationId) => `${base.compliance}/review/${applicationId}/reject`,
    resubmitApplication: (applicationId) => `${base.compliance}/review/${applicationId}/resubmit`,
    suspendApplication: (applicationId) => `${base.compliance}/review/${applicationId}/suspend`,
    escalateApplication: (applicationId) => `${base.compliance}/review/${applicationId}/escalate`,
    documentTypes: `${base.compliance}/document-types`,
    documentType: (documentTypeId) => `${base.compliance}/document-types/${documentTypeId}`,
    verificationProviders: `${base.compliance}/verification-providers`,
    verificationProvider: (providerId) => `${base.compliance}/verification-providers/${providerId}`,
    riskFlags: `${base.compliance}/risk-flags`,
    riskFlag: (flagId) => `${base.compliance}/risk-flags/${flagId}`,
    resolveRiskFlag: (flagId) => `${base.compliance}/risk-flags/${flagId}/resolve`,
    riskFlagSeverityBreakdown: `${base.compliance}/risk-flags/severity-breakdown`,
    auditEntries: `${base.compliance}/audit`,
    auditByResource: (resourceType, resourceId) =>
      `${base.compliance}/audit/resources/${resourceType}/${resourceId}`,
    actorSummary: (actorId) => `${base.compliance}/audit/actors/${actorId}/summary`,
    reportSummary: `${base.compliance}/reports/summary`,
    reportKycStatus: `${base.compliance}/reports/kyc-status`,
    reportApprovalRate: `${base.compliance}/reports/approval-rate`,
    reportRiskFlags: `${base.compliance}/reports/risk-flags`,
    reportReviewerPerformance: `${base.compliance}/reports/reviewer-performance`,
    reportDocumentUsage: `${base.compliance}/reports/document-usage`,
    reportExport: `${base.compliance}/reports/export`,
  },
  executive: {
    dashboard: `${base.executive}/dashboard`,
    revenue: `${base.executive}/revenue`,
    growth: `${base.executive}/growth`,
    retention: `${base.executive}/retention`,
    conversion: `${base.executive}/conversion`,
    financialReport: `${base.executive}/financial-report`,
  },
  support: {
    tickets: `${base.support}/tickets`,
    createTicket: `${base.support}/tickets`,
    ticket: (ticketId) => `${base.support}/tickets/${ticketId}`,
    addMessage: (ticketId) => `${base.support}/tickets/${ticketId}/messages`,
    closeTicket: (ticketId) => `${base.support}/tickets/${ticketId}/close`,
    myTickets: `${base.support}/tickets/my`,
    stats: `${base.support}/tickets/stats`,
    knowledgeBase: `${base.support}/knowledge-base`,
    article: (slug) => `${base.support}/knowledge-base/${slug}`,
    searchArticles: `${base.support}/knowledge-base/search`,
    articleCategories: `${base.support}/knowledge-base/categories`,
  },
  solana: {
    overview: `${base.solana}/overview`,
    network: `${base.solana}/network`,
    programs: `${base.solana}/programs`,
    health: `${base.solana}/health`,
    wallets: `${base.solana}/wallets`,
    wallet: (walletId) => `${base.solana}/wallets/${walletId}`,
    primaryWallet: `${base.solana}/wallets/primary`,
    walletCount: `${base.solana}/wallets/count`,
    beginConnect: `${base.solana}/wallets/siws/begin`,
    completeConnect: `${base.solana}/wallets/siws/complete`,
    setPrimary: (walletId) => `${base.solana}/wallets/${walletId}/set-primary`,
    updateWalletLabel: (walletId) => `${base.solana}/wallets/${walletId}/label`,
    disconnectWallet: (walletId) => `${base.solana}/wallets/${walletId}`,
    attestations: `${base.solana}/attestations`,
    attestation: (attestationId) => `${base.solana}/attestations/${attestationId}`,
    attestationBySubject: (subjectType, subjectId) =>
      `${base.solana}/attestations/subject/${subjectType}/${subjectId}`,
    revokeAttestation: (attestationId) => `${base.solana}/attestations/${attestationId}/revoke`,
    pendingAttestations: `${base.solana}/attestations/pending`,
    attestationStatusBreakdown: `${base.solana}/attestations/status-breakdown`,
    provenanceBySignal: (signalId) => `${base.solana}/provenance/signals/${signalId}`,
    provenance: (provenanceId) => `${base.solana}/provenance/${provenanceId}`,
    provenanceByProvider: (providerId) => `${base.solana}/provenance/providers/${providerId}`,
    verifyProcessingHash: `${base.solana}/provenance/verify`,
    confirmProvenanceAnchor: (provenanceId) => `${base.solana}/provenance/${provenanceId}/confirm`,
    failProvenanceAnchor: (provenanceId) => `${base.solana}/provenance/${provenanceId}/fail`,
    pendingProvenance: `${base.solana}/provenance/pending`,
    provenanceStatusBreakdown: `${base.solana}/provenance/status-breakdown`,
    payments: `${base.solana}/payments`,
    createPayment: `${base.solana}/payments`,
    payment: (paymentId) => `${base.solana}/payments/${paymentId}`,
    attachSignature: (paymentId) => `${base.solana}/payments/${paymentId}/attach-signature`,
    verifyPayment: (paymentId) => `${base.solana}/payments/${paymentId}/verify`,
    confirmPayment: (paymentId) => `${base.solana}/payments/${paymentId}/confirm`,
    markPaymentConfirmed: (paymentId) => `${base.solana}/payments/${paymentId}/mark-confirmed`,
    markPaymentFailed: (paymentId) => `${base.solana}/payments/${paymentId}/mark-failed`,
    refundPayment: (paymentId) => `${base.solana}/payments/${paymentId}/refund`,
    sweepPendingPayments: `${base.solana}/payments/sweep/pending`,
    sweepExpiredPayments: `${base.solana}/payments/sweep/expired`,
    paymentStatusBreakdown: `${base.solana}/payments/status-breakdown`,
  },
  verification: {
    attestationById: (attestationId) => `${base.verification}/attestations/id/${attestationId}`,
    attestationByHash: (hash) => `${base.verification}/attestations/hash/${hash}`,
    signalProvenance: (signalId) => `${base.verification}/signals/${signalId}`,
    processingHash: (hash) => `${base.verification}/processing/${hash}`,
    auditAttestation: (attestationId) => `${base.verification}/audit/attestations/${attestationId}`,
    auditProvenance: (provenanceId) => `${base.verification}/audit/provenance/${provenanceId}`,
    auditPending: `${base.verification}/audit/pending`,
  },
  webhooks: {
    stripe: `${base.webhooks}/stripe`,
    paystack: `${base.webhooks}/paystack`,
    flutterwave: `${base.webhooks}/flutterwave`,
    kycSmileId: `${base.webhooks}/kyc/smileid`,
    kycVerifyMe: `${base.webhooks}/kyc/verifyme`,
    tradingview: (routeToken) => `/api/webhooks/tradingview/${routeToken}`,
  },
});

export default endpoints;