import React, { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { FileText, ArrowLeft, Gift, TrendingUp, Shield, Clock, Wallet } from 'lucide-react';
import Container from '../../components/ui/primitives/Container';
import Card from '../../components/common/Card';
import Heading from '../../components/ui/primitives/Heading';
import Text from '../../components/ui/primitives/Text';
import Button from '../../components/common/Button';

const SECTIONS = [
  {
    icon: Gift,
    title: 'How Referrals Work',
    content:
      'When you share your unique referral link and someone creates an account through it, that user is permanently attributed to you as a referred user. You earn a reward based on the eligible net trading performance generated by each referred user.',
  },
  {
    icon: TrendingUp,
    title: 'Reward Calculation',
    content:
      'The reward is calculated as a percentage of the eligible net trading profit generated by each referred user in a given settlement period. The default reward rate is 0.1%. If a referred user\'s net result for the period is negative, the eligible profit is floored at $0 and no reward is issued.',
  },
  {
    icon: Clock,
    title: 'Monthly Settlement',
    content:
      'Rewards are calculated once per month during the monthly settlement run. The settlement process freezes the period, computes eligible net profit, applies the reward rate, runs integrity checks, and credits your referral wallet.',
  },
  {
    icon: Wallet,
    title: 'Wallet and Withdrawals',
    content:
      'Referral rewards accumulate in your referral wallet. Rewards in the "pending" state become "available" after settlement. You can withdraw available rewards or use them for SignalForge subscriptions, subject to KYC verification.',
  },
  {
    icon: Shield,
    title: 'Fraud Protection',
    content:
      'Referral rewards may be placed in an "under review" state if fraud indicators are detected, including self-referral, duplicate accounts, manipulated trading volume, or abnormal activity. Confirmed fraud may result in reward reversal and account suspension.',
  },
  {
    icon: TrendingUp,
    title: 'Platform-Funded Rewards',
    content:
      'Referral rewards are funded from SignalForge\'s designated referral pool and never deducted from the referred user\'s trading profits or account balance.',
  },
];

const ReferralTerms = function ReferralTerms() {
  const navigate = useNavigate();

  const handleBack = useCallback(() => navigate('/referrals'), [navigate]);

  return (
    <Container size="lg" className="py-6">
      <Button variant="ghost" size="sm" onClick={handleBack} leadingIcon={ArrowLeft}>
        Back
      </Button>

      <div className="mt-4">
        <div className="flex items-center gap-3">
          <span className="flex h-11 w-11 items-center justify-center rounded-lg bg-violet-50 text-violet-600">
            <FileText size={20} aria-hidden="true" />
          </span>
          <div>
            <Heading level={1} size="text-2xl">
              Referral Program Terms
            </Heading>
            <Text color="muted" className="text-xs">
              The rules and conditions of the SignalForge referral program
            </Text>
          </div>
        </div>

        <div className="mt-6 space-y-4">
          {SECTIONS.map((section) => {
            const Icon = section.icon;
            return (
              <Card key={section.title} padding="lg">
                <div className="flex items-start gap-4">
                  <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-violet-50 text-violet-600">
                    <Icon size={20} aria-hidden="true" />
                  </span>
                  <div className="min-w-0 flex-1">
                    <h3 className="text-base font-semibold text-slate-900">{section.title}</h3>
                    <p className="mt-2 text-sm leading-relaxed text-slate-600">
                      {section.content}
                    </p>
                  </div>
                </div>
              </Card>
            );
          })}
        </div>

        <Card padding="lg" className="mt-6">
          <Heading level={3} size="text-base">
            Additional Terms
          </Heading>
          <ul className="mt-3 space-y-2 text-sm text-slate-600">
            <li>· A referral relationship, once attributed, is permanent. Users cannot switch referrers.</li>
            <li>· Each referred user maps to exactly one referrer. Duplicate attributions are not permitted.</li>
            <li>· Reward eligibility requires successful KYC verification for the referrer.</li>
            <li>· SignalForge reserves the right to adjust the reward rate with advance notice.</li>
            <li>· Referral rewards are subject to applicable tax laws in your jurisdiction.</li>
            <li>· The referral program is provided at SignalForge's discretion and may be modified or discontinued.</li>
          </ul>
        </Card>
      </div>
    </Container>
  );
};

export default ReferralTerms;