/**
 * Route Configuration
 *
 * Central definition of every route path. Components and hooks import
 * from here so paths are never duplicated as string literals.
 *
 * @module client/src/config/routes.config
 */

export const routes = Object.freeze({
  public: {
    home: '/',
    howItWorks: '/how-it-works',
    features: '/features',
    featuresAi: '/features/ai',
    featuresAutomatedTrading: '/features/automated-trading',
    featuresRisk: '/features/risk',
    featuresCopyTrading: '/features/copy-trading',
    featuresAnalytics: '/features/analytics',
    featuresMarketplace: '/features/marketplace',
    pricing: '/pricing',
    enterprise: '/enterprise',
    whiteLabel: '/white-label',
    apiPlatform: '/api-platform',
    security: '/security',
    about: '/about',
    contact: '/contact',
    faq: '/faq',
    legal: '/legal',
    privacy: '/privacy',
    terms: '/terms',
  },
  auth: {
    login: '/login',
    register: '/register',
    emailVerification: '/verify-email',
    phoneVerification: '/verify-phone',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    twoFactorSetup: '/2fa/setup',
    twoFactorVerify: '/2fa/verify',
    accountRecovery: '/account-recovery',
    sessionVerification: '/session-verification',
    logout: '/logout',
  },
  onboarding: {
    welcome: '/welcome',
    flow: '/onboarding',
    complete: '/onboarding/complete',
  },
  kyc: {
    intro: '/kyc',
    personalInfo: '/kyc/personal-info',
    documentSelection: '/kyc/document-selection',
    documentUpload: '/kyc/document-upload',
    documentVerification: '/kyc/document-verification',
    selfieVerification: '/kyc/selfie-verification',
    reviewStatus: '/kyc/review-status',
    result: '/kyc/result',
    resubmission: '/kyc/resubmission',
    expired: '/kyc/expired',
    help: '/kyc/help',
    statusDashboard: '/kyc/status',
  },
  user: {
    dashboard: '/dashboard',
    accountSummary: '/dashboard/account-summary',
    portfolioOverview: '/dashboard/portfolio',
    liveTradingStatus: '/dashboard/live-trading',
    signalCenter: {
      root: '/signals',
      live: '/signals/live',
      history: '/signals/history',
      details: (signalId = ':signalId') => `/signals/${signalId}`,
      processingTimeline: (signalId = ':signalId') => `/signals/${signalId}/timeline`,
      confidence: (signalId = ':signalId') => `/signals/${signalId}/confidence`,
      riskAnalysis: (signalId = ':signalId') => `/signals/${signalId}/risk`,
      providerSignals: '/signals/providers',
      duplicates: '/signals/duplicates',
      consensus: '/signals/consensus',
      rejected: '/signals/rejected',
      replay: (signalId = ':signalId') => `/signals/${signalId}/replay`,
    },
    signalSources: {
      overview: '/signal-sources',
      add: '/signal-sources/add',
      telegramConnection: '/signal-sources/telegram',
      telegramChannels: '/signal-sources/telegram/channels',
      discordConnection: '/signal-sources/discord',
      discordChannels: '/signal-sources/discord/channels',
      whatsappConnection: '/signal-sources/whatsapp',
      whatsappSources: '/signal-sources/whatsapp/sources',
      tradingviewWebhooks: '/signal-sources/tradingview',
      restApiSources: '/signal-sources/rest-api',
      emailSources: '/signal-sources/email',
      messageInbox: '/signal-sources/messages',
      messageDetails: (messageId = ':messageId') => `/signal-sources/messages/${messageId}`,
      processingLogs: '/signal-sources/logs',
    },
    aiIntelligence: {
      overview: '/ai-intelligence',
      parser: '/ai-intelligence/parser',
      interpretation: '/ai-intelligence/interpretation',
      providerDna: '/ai-intelligence/provider-dna',
      providerDnaRules: '/ai-intelligence/provider-dna/rules',
      learningActivity: '/ai-intelligence/learning',
      confidenceEngine: '/ai-intelligence/confidence',
      riskIntelligence: '/ai-intelligence/risk',
      multilingual: '/ai-intelligence/multilingual',
      consensusEngine: '/ai-intelligence/consensus',
      duplicateDetection: '/ai-intelligence/duplicates',
      processingLogs: '/ai-intelligence/logs',
      modelPerformance: '/ai-intelligence/models',
      learningHistory: '/ai-intelligence/history',
    },
    providerDna: {
      root: '/provider-dna',
      overview: '/provider-dna/overview',
      languageProfile: '/provider-dna/language',
      symbolMapping: '/provider-dna/symbols',
      abbreviationMapping: '/provider-dna/abbreviations',
      tradeManagementRules: '/provider-dna/management-rules',
      riskBehavior: '/provider-dna/risk-behavior',
      learnedPatterns: '/provider-dna/patterns',
      confidence: '/provider-dna/confidence',
      versionHistory: '/provider-dna/versions',
      trainingMessages: '/provider-dna/training',
      test: '/provider-dna/test',
    },
    trading: {
      overview: '/trading',
      openPositions: '/trading/positions',
      positionDetails: (positionId = ':positionId') => `/trading/positions/${positionId}`,
      history: '/trading/history',
      tradeDetails: (tradeId = ':tradeId') => `/trading/${tradeId}`,
      pendingOrders: '/trading/pending-orders',
      closedTrades: '/trading/closed',
      manualInterventions: '/trading/manual-interventions',
      tradeEvents: '/trading/events',
      tradeTimeline: (tradeId = ':tradeId') => `/trading/${tradeId}/timeline`,
      tradeShadow: '/trading/shadow',
      tradeReplay: (tradeId = ':tradeId') => `/trading/${tradeId}/replay`,
      executionHistory: '/trading/execution-history',
    },
    riskAutomation: {
      overview: '/risk',
      profile: '/risk/profile',
      rules: '/risk/rules',
      dailyLossLimits: '/risk/daily-loss-limits',
      drawdownProtection: '/risk/drawdown-protection',
      maximumOpenTrades: '/risk/max-open-trades',
      tradingSessions: '/risk/trading-sessions',
      trailingStop: '/risk/trailing-stop',
      breakEven: '/risk/break-even',
      profitLock: '/risk/profit-lock',
      partialClose: '/risk/partial-close',
      correlationProtection: '/risk/correlation-protection',
      newsFilter: '/risk/news-filter',
      emergencyStop: '/risk/emergency-stop',
      automationRules: '/automation/rules',
      createRule: '/automation/rules/create',
      providerSpecificRules: '/automation/rules/provider',
      riskEvents: '/risk/events',
    },
    brokers: {
      accounts: '/brokers',
      connect: '/brokers/connect',
      mt4: '/brokers/mt4',
      mt5: '/brokers/mt5',
      accountDetails: (accountId = ':accountId') => `/brokers/${accountId}`,
      connectionStatus: '/brokers/status',
      balanceEquity: '/brokers/balance',
      synchronization: '/brokers/sync',
      connectionLogs: '/brokers/logs',
      disconnect: '/brokers/disconnect',
    },
    analytics: {
      overview: '/analytics',
      performanceDashboard: '/analytics/performance',
      equityCurve: '/analytics/equity-curve',
      profit: '/analytics/profit',
      drawdown: '/analytics/drawdown',
      winRate: '/analytics/win-rate',
      riskReward: '/analytics/risk-reward',
      sharpeRatio: '/analytics/sharpe',
      sortinoRatio: '/analytics/sortino',
      bestSymbols: '/analytics/best-symbols',
      worstSymbols: '/analytics/worst-symbols',
      executionLatency: '/analytics/execution-latency',
      riskBehavior: '/analytics/risk-behavior',
      calendar: '/analytics/calendar',
      reports: '/analytics/reports',
      export: '/analytics/export',
    },
    providerMarketplace: {
      browse: '/marketplace/providers',
      search: '/marketplace/providers/search',
      categories: '/marketplace/providers/categories',
      profile: (providerId = ':providerId') => `/marketplace/providers/${providerId}`,
      performance: (providerId = ':providerId') => `/marketplace/providers/${providerId}/performance`,
      signals: (providerId = ':providerId') => `/marketplace/providers/${providerId}/signals`,
      reviews: (providerId = ':providerId') => `/marketplace/providers/${providerId}/reviews`,
      riskAnalysis: (providerId = ':providerId') => `/marketplace/providers/${providerId}/risk`,
      subscribers: (providerId = ':providerId') => `/marketplace/providers/${providerId}/subscribers`,
      subscriptionPlans: (providerId = ':providerId') => `/marketplace/providers/${providerId}/plans`,
      subscribe: (providerId = ':providerId') => `/marketplace/providers/${providerId}/subscribe`,
      myProviders: '/marketplace/providers/my',
      comparison: '/marketplace/providers/compare',
      consensus: '/marketplace/providers/consensus',
    },
    traderMarketplace: {
      browse: '/marketplace/traders',
      search: '/marketplace/traders/search',
      categories: '/marketplace/traders/categories',
      profile: (traderId = ':traderId') => `/marketplace/traders/${traderId}`,
      performance: (traderId = ':traderId') => `/marketplace/traders/${traderId}/performance`,
      risk: (traderId = ':traderId') => `/marketplace/traders/${traderId}/risk`,
      behavior: (traderId = ':traderId') => `/marketplace/traders/${traderId}/behavior`,
      intelligence: (traderId = ':traderId') => `/marketplace/traders/${traderId}/intelligence`,
      reviews: (traderId = ':traderId') => `/marketplace/traders/${traderId}/reviews`,
      tradingStyle: (traderId = ':traderId') => `/marketplace/traders/${traderId}/style`,
      follow: (traderId = ':traderId') => `/marketplace/traders/${traderId}/follow`,
      copySettings: '/marketplace/traders/copy-settings',
      myFollowed: '/marketplace/traders/my',
    },
    traderIntelligence: {
      overview: '/trader-intelligence',
      consistency: '/trader-intelligence/consistency',
      averageRiskReward: '/trader-intelligence/average-risk-reward',
      holdingTime: '/trader-intelligence/holding-time',
      riskBehavior: '/trader-intelligence/risk-behavior',
      martingaleGrid: '/trader-intelligence/martingale-grid',
      newsExposure: '/trader-intelligence/news-exposure',
      recoveryTrading: '/trader-intelligence/recovery-trading',
      styleClassification: '/trader-intelligence/style',
      behaviorTimeline: '/trader-intelligence/timeline',
    },
    referrals: {
      dashboard: '/referrals',
      link: '/referrals/link',
      invite: '/referrals/invite',
      network: '/referrals/network',
      referredUsers: '/referrals/users',
      performance: '/referrals/performance',
      earnings: '/referrals/earnings',
      pendingRewards: '/referrals/rewards/pending',
      availableRewards: '/referrals/rewards/available',
      wallet: '/referrals/wallet',
      rewardHistory: '/referrals/rewards/history',
      monthlySettlement: '/referrals/settlement',
      leaderboard: '/referrals/leaderboard',
      terms: '/referrals/terms',
    },
    subscriptions: {
      plans: '/subscriptions/plans',
      checkout: '/subscriptions/checkout',
      mySubscription: '/subscriptions/my',
      upgrade: '/subscriptions/upgrade',
      downgrade: '/subscriptions/downgrade',
      billingHistory: '/subscriptions/billing',
      invoice: (invoiceId = ':invoiceId') => `/subscriptions/invoices/${invoiceId}`,
      paymentMethods: '/subscriptions/payment-methods',
      usage: '/subscriptions/usage',
      cancel: '/subscriptions/cancel',
    },
    wallet: {
      overview: '/wallet',
      availableBalance: '/wallet/available',
      pendingBalance: '/wallet/pending',
      transactions: '/wallet/transactions',
      withdrawalRequest: '/wallet/withdraw',
      withdrawalStatus: '/wallet/withdrawals/status',
      withdrawalHistory: '/wallet/withdrawals/history',
      paymentAccounts: '/wallet/payment-accounts',
    },
    providerBusiness: {
      dashboard: '/provider',
      profile: '/provider/profile',
      subscribers: '/provider/subscribers',
      revenue: '/provider/revenue',
      analytics: '/provider/analytics',
      signals: '/provider/signals',
      dna: '/provider/dna',
      certification: '/provider/certification',
      plans: '/provider/plans',
      withdrawals: '/provider/withdrawals',
      ib: '/provider/ib',
      affiliate: '/provider/affiliate',
      marketing: '/provider/marketing',
      promotions: '/provider/promotions',
      reviews: '/provider/reviews',
      settings: '/provider/settings',
    },
    providerCertification: {
      dashboard: '/provider-certification',
      importHistory: '/provider-certification/import',
      trainingDataset: '/provider-certification/dataset',
      parsingAccuracy: '/provider-certification/parsing',
      backtesting: '/provider-certification/backtesting',
      expectedPerformance: '/provider-certification/performance',
      riskAssessment: '/provider-certification/risk',
      consistencyScore: '/provider-certification/consistency',
      qualityScore: '/provider-certification/quality',
      result: '/provider-certification/result',
      history: '/provider-certification/history',
    },
    affiliate: {
      dashboard: '/affiliate',
      links: '/affiliate/links',
      referrals: '/affiliate/referrals',
      commissions: '/affiliate/commissions',
    },
    ib: {
      dashboard: '/ib',
      brokerReferralLinks: '/ib/links',
      referrals: '/ib/referrals',
      revenue: '/ib/revenue',
      commissionHistory: '/ib/commissions',
    },
    whiteLabel: {
      dashboard: '/white-label',
      branding: '/white-label/branding',
      logo: '/white-label/logo',
      domains: '/white-label/domains',
      theme: '/white-label/theme',
      pricing: '/white-label/pricing',
      analytics: '/white-label/analytics',
      users: '/white-label/users',
      revenue: '/white-label/revenue',
      settings: '/white-label/settings',
    },
    notifications: {
      center: '/notifications',
      trades: '/notifications/trades',
      signals: '/notifications/signals',
      kyc: '/notifications/kyc',
      referrals: '/notifications/referrals',
      payments: '/notifications/payments',
      security: '/notifications/security',
      system: '/notifications/system',
      preferences: '/notifications/preferences',
    },
    settings: {
      profile: '/settings/profile',
      account: '/settings/account',
      security: '/settings/security',
      twoFactor: '/settings/2fa',
      devices: '/settings/devices',
      connectedAccounts: '/settings/accounts',
      brokers: '/settings/brokers',
      signalSources: '/settings/signal-sources',
      tradingPreferences: '/settings/trading',
      riskPreferences: '/settings/risk',
      notifications: '/settings/notifications',
      privacy: '/settings/privacy',
      apiKeys: '/settings/api-keys',
      dataPrivacy: '/settings/data-privacy',
      deleteAccount: '/settings/delete-account',
    },
    admin: {
      overview: '/admin',
      users: '/admin/users',
      userDetails: (userId = ':userId') => `/admin/users/${userId}`,
      userRestrictions: (userId = ':userId') => `/admin/users/${userId}/restrictions`,
      kyc: '/admin/kyc',
      providers: '/admin/providers',
      traders: '/admin/traders',
      signalSources: '/admin/signal-sources',
      brokers: '/admin/brokers',
      liveTradeMonitor: '/admin/trades/monitor',
      liveSignalMonitor: '/admin/signals/monitor',
      aiMonitoring: '/admin/ai',
      providerDnaMonitoring: '/admin/provider-dna',
      riskMonitoring: '/admin/risk',
      referrals: '/admin/referrals',
      subscriptions: '/admin/subscriptions',
      payments: '/admin/payments',
      withdrawals: '/admin/withdrawals',
      affiliate: '/admin/affiliate',
      marketplaceModeration: '/admin/marketplace',
      reports: '/admin/reports',
      systemAnalytics: '/admin/analytics',
      auditLogs: '/admin/audit-logs',
      securityCenter: '/admin/security',
      systemSettings: '/admin/settings',
    },
    compliance: {
      dashboard: '/compliance',
      kycQueue: '/compliance/kyc-queue',
      pending: '/compliance/kyc-queue/pending',
      underReview: '/compliance/kyc-queue/under-review',
      verified: '/compliance/kyc-queue/verified',
      rejected: '/compliance/kyc-queue/rejected',
      suspended: '/compliance/kyc-queue/suspended',
      documentTypes: '/compliance/document-types',
      verificationProviders: '/compliance/verification-providers',
      riskFlags: '/compliance/risk-flags',
      reports: '/compliance/reports',
      auditTrail: '/compliance/audit',
    },
    executive: {
      dashboard: '/executive',
      subscriptionRevenue: '/executive/revenue/subscriptions',
      marketplaceRevenue: '/executive/revenue/marketplace',
      providerRevenue: '/executive/revenue/providers',
      affiliateRevenue: '/executive/revenue/affiliate',
      ibRevenue: '/executive/revenue/ib',
      referralCost: '/executive/revenue/referral-cost',
      netRevenue: '/executive/revenue/net',
      userGrowth: '/executive/growth/users',
      providerGrowth: '/executive/growth/providers',
      traderGrowth: '/executive/growth/traders',
      tradingVolume: '/executive/volume',
      platformPerformance: '/executive/performance',
      retention: '/executive/retention',
      conversion: '/executive/conversion',
      financialReports: '/executive/financial-reports',
    },
    support: {
      helpCenter: '/support',
      dashboard: '/support/dashboard',
      createTicket: '/support/tickets/create',
      ticketDetails: (ticketId = ':ticketId') => `/support/tickets/${ticketId}`,
      myTickets: '/support/tickets',
      knowledgeBase: '/support/knowledge-base',
      tradingFaq: '/support/faq/trading',
      kycFaq: '/support/faq/kyc',
      billingFaq: '/support/faq/billing',
      technicalSupport: '/support/technical',
    },
    replay: {
      center: '/replay',
      signalReplay: (signalId = ':signalId') => `/replay/signals/${signalId}`,
      tradeReplay: (tradeId = ':tradeId') => `/replay/trades/${tradeId}`,
      aiReplay: (signalId = ':signalId') => `/replay/ai/${signalId}`,
      riskReplay: (signalId = ':signalId') => `/replay/risk/${signalId}`,
      executionReplay: (tradeId = ':tradeId') => `/replay/execution/${tradeId}`,
      providerMessageReplay: (messageId = ':messageId') => `/replay/providers/${messageId}`,
      systemTimeline: (correlationId = ':correlationId') => `/replay/system/${correlationId}`,
    },
    solana: {
      walletConnect: '/solana/wallet/connect',
      walletSettings: '/solana/wallet/settings',
      reputation: '/solana/reputation',
      provenanceExplorer: '/solana/provenance',
      attestationViewer: '/solana/attestations',
      paymentCheckout: '/solana/payments/checkout',
      paymentHistory: '/solana/payments/history',
      publicVerification: (hash = ':hash') => `/verify/${hash}`,
      onChainBadges: '/solana/badges',
    },
  },
});

export const publicRoutes = Object.values(routes.public);
export const protectedRoutes = {
  ...routes.user,
  ...routes.providerBusiness,
  ...routes.providerCertification,
  ...routes.affiliate,
  ...routes.ib,
  ...routes.whiteLabel,
  ...routes.notifications,
  ...routes.settings,
  ...routes.referrals,
  ...routes.subscriptions,
  ...routes.wallet,
  ...routes.solana,
};
export const adminRoutes = routes.admin;
export const complianceRoutes = routes.compliance;
export const executiveRoutes = routes.executive;
export const supportRoutes = routes.support;

export default routes;