/**
 * Actor Attribution Service
 *
 * @module signalforge/server/modules/trade-state/lifecycle/actor-attribution
 */

import { TRADE_ACTORS, isValidTradeActor } from '../trade-state.constants.js';
import { InvalidTradeActorError } from '../trade-state.errors.js';

const EVENT_ACTOR_MAP = Object.freeze({
  SIGNAL_RECEIVED: TRADE_ACTORS.PROVIDER,
  SIGNAL_UPDATED: TRADE_ACTORS.PROVIDER,
  SIGNAL_DELETED: TRADE_ACTORS.PROVIDER,
  PARSED: TRADE_ACTORS.SYSTEM,
  CLASSIFIED: TRADE_ACTORS.SYSTEM,
  PROVIDER_DNA_MATCHED: TRADE_ACTORS.SYSTEM,
  VALIDATED: TRADE_ACTORS.SYSTEM,
  VALIDATION_FAILED: TRADE_ACTORS.SYSTEM,
  DUPLICATE_DETECTED: TRADE_ACTORS.SYSTEM,
  CONFLICT_DETECTED: TRADE_ACTORS.SYSTEM,
  CONSENSUS_REACHED: TRADE_ACTORS.SYSTEM,
  CONSENSUS_FAILED: TRADE_ACTORS.SYSTEM,
  RISK_APPROVED: TRADE_ACTORS.RISK_ENGINE,
  RISK_REJECTED: TRADE_ACTORS.RISK_ENGINE,
  AUTOMATION_RULE_TRIGGERED: TRADE_ACTORS.AUTO_RULE,
  EXECUTION_REQUESTED: TRADE_ACTORS.SYSTEM,
  EXECUTION_ACCEPTED: TRADE_ACTORS.BROKER,
  EXECUTION_REJECTED: TRADE_ACTORS.BROKER,
  EXECUTION_FAILED: TRADE_ACTORS.SYSTEM,
  EXECUTION_RETRY: TRADE_ACTORS.SYSTEM,
  EXECUTED: TRADE_ACTORS.BROKER,
  PENDING_ORDER_PLACED: TRADE_ACTORS.BROKER,
  PENDING_ORDER_CANCELLED: TRADE_ACTORS.USER,
  POSITION_OPENED: TRADE_ACTORS.BROKER,
  POSITION_MODIFIED: TRADE_ACTORS.USER,
  SL_MODIFIED: TRADE_ACTORS.USER,
  TP_MODIFIED: TRADE_ACTORS.USER,
  BREAK_EVEN: TRADE_ACTORS.AUTO_RULE,
  TRAILING_STOP: TRADE_ACTORS.AUTO_RULE,
  PARTIAL_CLOSE: TRADE_ACTORS.AUTO_RULE,
  MANUAL_CLOSE: TRADE_ACTORS.USER,
  MANUAL_MODIFY: TRADE_ACTORS.USER,
  AUTO_CLOSE: TRADE_ACTORS.AUTO_RULE,
  PROVIDER_CLOSE: TRADE_ACTORS.PROVIDER,
  RISK_CLOSE: TRADE_ACTORS.RISK_ENGINE,
  EMERGENCY_STOP: TRADE_ACTORS.USER,
  STOP_LOSS: TRADE_ACTORS.BROKER,
  TAKE_PROFIT: TRADE_ACTORS.BROKER,
  CLOSED: TRADE_ACTORS.SYSTEM,
  ARCHIVED: TRADE_ACTORS.SYSTEM,
  SHADOW_COMPARISON: TRADE_ACTORS.SYSTEM,
  SOLANA_PROVENANCE_ANCHORED: TRADE_ACTORS.SYSTEM,
});

export class ActorAttributionService {
  deriveActor(eventType, explicitActor = null) {
    if (explicitActor) {
      if (!isValidTradeActor(explicitActor)) {
        throw new InvalidTradeActorError(undefined, { actor: explicitActor });
      }
      return explicitActor;
    }
    return EVENT_ACTOR_MAP[eventType] || TRADE_ACTORS.SYSTEM;
  }

  isUserAction(actor) {
    return actor === TRADE_ACTORS.USER;
  }

  isSystemAction(actor) {
    return actor === TRADE_ACTORS.SYSTEM;
  }

  isAutoRuleAction(actor) {
    return actor === TRADE_ACTORS.AUTO_RULE;
  }
}

export default ActorAttributionService;