/**
 * Error Codes
 *
 * Central registry of application error codes. Grouped by domain.
 * Consumed by AppError subclasses and the HTTP error middleware.
 *
 * @module server/lib/errors/error-codes
 */

export const ERROR_CODES = Object.freeze({
  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  CONFIGURATION_MISSING: 'CONFIGURATION_MISSING',
  CONFIGURATION_INVALID: 'CONFIGURATION_INVALID',

  // Authentication / Authorization
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  AUTHORIZATION_FAILED: 'AUTHORIZATION_FAILED',
  EMAIL_VERIFICATION_REQUIRED: 'EMAIL_VERIFICATION_REQUIRED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  RATE_LIMITED: 'RATE_LIMITED',

  // KYC
  KYC_REQUIRED: 'KYC_REQUIRED',
  KYC_NOT_FOUND: 'KYC_NOT_FOUND',
  KYC_ALREADY_VERIFIED: 'KYC_ALREADY_VERIFIED',
  KYC_DOCUMENT_INVALID: 'KYC_DOCUMENT_INVALID',
  KYC_DOCUMENT_TOO_LARGE: 'KYC_DOCUMENT_TOO_LARGE',

  // Subscription
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE',
  SUBSCRIPTION_PLAN_NOT_FOUND: 'SUBSCRIPTION_PLAN_NOT_FOUND',

  // Payments
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_COMPLETED: 'PAYMENT_ALREADY_COMPLETED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',

  // Brokers
  BROKER_NOT_FOUND: 'BROKER_NOT_FOUND',
  BROKER_ACCOUNT_NOT_FOUND: 'BROKER_ACCOUNT_NOT_FOUND',
  BROKER_CONNECTION_FAILED: 'BROKER_CONNECTION_FAILED',
  BROKER_REJECTED_ORDER: 'BROKER_REJECTED_ORDER',

  // Signals & Trades
  SIGNAL_NOT_FOUND: 'SIGNAL_NOT_FOUND',
  SIGNAL_INVALID: 'SIGNAL_INVALID',
  TRADE_NOT_FOUND: 'TRADE_NOT_FOUND',
  TRADE_EXECUTION_FAILED: 'TRADE_EXECUTION_FAILED',
  TRADE_ALREADY_CLOSED: 'TRADE_ALREADY_CLOSED',
  RISK_REJECTED: 'RISK_REJECTED',

  // Signal Sources
  SOURCE_TYPE_UNKNOWN: 'SOURCE_TYPE_UNKNOWN',
  SOURCE_ADAPTER_INVALID: 'SOURCE_ADAPTER_INVALID',
  SOURCE_ADAPTER_DUPLICATE: 'SOURCE_ADAPTER_DUPLICATE',
  SOURCE_ADAPTER_NOT_FOUND: 'SOURCE_ADAPTER_NOT_FOUND',
  TELEGRAM_SESSION_NOT_FOUND: 'TELEGRAM_SESSION_NOT_FOUND',
  TELEGRAM_SESSION_DECRYPT_FAILED: 'TELEGRAM_SESSION_DECRYPT_FAILED',
  TELEGRAM_SEND_CODE_FAILED: 'TELEGRAM_SEND_CODE_FAILED',
  TELEGRAM_SIGNIN_FAILED: 'TELEGRAM_SIGNIN_FAILED',
  TELEGRAM_2FA_REQUIRED: 'TELEGRAM_2FA_REQUIRED',
  TELEGRAM_2FA_INVALID: 'TELEGRAM_2FA_INVALID',
  TELEGRAM_2FA_FAILED: 'TELEGRAM_2FA_FAILED',
  TELEGRAM_CODE_INVALID: 'TELEGRAM_CODE_INVALID',
  TELEGRAM_CODE_EXPIRED: 'TELEGRAM_CODE_EXPIRED',
  TELEGRAM_RATE_LIMIT: 'TELEGRAM_RATE_LIMIT',
  TELEGRAM_NO_CHANNELS: 'TELEGRAM_NO_CHANNELS',
  TELEGRAM_CHANNEL_INVALID: 'TELEGRAM_CHANNEL_INVALID',
  TELEGRAM_CHANNEL_LIMIT_EXCEEDED: 'TELEGRAM_CHANNEL_LIMIT_EXCEEDED',
  TELEGRAM_MESSAGE_INVALID: 'TELEGRAM_MESSAGE_INVALID',
  TELEGRAM_LISTENER_START_FAILED: 'TELEGRAM_LISTENER_START_FAILED',
  TELEGRAM_DISCOVERY_FAILED: 'TELEGRAM_DISCOVERY_FAILED',
  TELEGRAM_CLIENT_INVALID: 'TELEGRAM_CLIENT_INVALID',
  TELEGRAM_CLIENT_NOT_IMPLEMENTED: 'TELEGRAM_CLIENT_NOT_IMPLEMENTED',
  DISCORD_OAUTH_FAILED: 'DISCORD_OAUTH_FAILED',
  DISCORD_DISCOVERY_FAILED: 'DISCORD_DISCOVERY_FAILED',
  DISCORD_MESSAGE_INVALID: 'DISCORD_MESSAGE_INVALID',
  DISCORD_CONNECTION_NOT_FOUND: 'DISCORD_CONNECTION_NOT_FOUND',
  DISCORD_DECRYPT_FAILED: 'DISCORD_DECRYPT_FAILED',
  DISCORD_WEBHOOK_INVALID: 'DISCORD_WEBHOOK_INVALID',
  DISCORD_WEBHOOK_SEND_FAILED: 'DISCORD_WEBHOOK_SEND_FAILED',
  WHATSAPP_WEBHOOK_INVALID: 'WHATSAPP_WEBHOOK_INVALID',
  WHATSAPP_CONNECTION_NOT_FOUND: 'WHATSAPP_CONNECTION_NOT_FOUND',
  WHATSAPP_DECRYPT_FAILED: 'WHATSAPP_DECRYPT_FAILED',
  WHATSAPP_CLOUD_FAILED: 'WHATSAPP_CLOUD_FAILED',
  WHATSAPP_SEND_FAILED: 'WHATSAPP_SEND_FAILED',
  TRADINGVIEW_WEBHOOK_INVALID: 'TRADINGVIEW_WEBHOOK_INVALID',
  TRADINGVIEW_WEBHOOK_EXPIRED: 'TRADINGVIEW_WEBHOOK_EXPIRED',
  EMAIL_DECRYPT_FAILED: 'EMAIL_DECRYPT_FAILED',
  EMAIL_CONNECTION_NOT_FOUND: 'EMAIL_CONNECTION_NOT_FOUND',
  EMAIL_LISTENER_START_FAILED: 'EMAIL_LISTENER_START_FAILED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  EMAIL_PARSE_FAILED: 'EMAIL_PARSE_FAILED',
  EMAIL_ATTACHMENT_LIMIT_EXCEEDED: 'EMAIL_ATTACHMENT_LIMIT_EXCEEDED',
  EMAIL_BODY_TOO_LARGE: 'EMAIL_BODY_TOO_LARGE',
  REST_API_PAYLOAD_TOO_LARGE: 'REST_API_PAYLOAD_TOO_LARGE',

  // AI
  AI_PARSE_FAILED: 'AI_PARSE_FAILED',
  AI_PARSE_VALIDATION_FAILED: 'AI_PARSE_VALIDATION_FAILED',

  // Notifications
  NOTIFICATION_CHANNEL_UNAVAILABLE: 'NOTIFICATION_CHANNEL_UNAVAILABLE',
  NOTIFICATION_SEND_FAILED: 'NOTIFICATION_SEND_FAILED',

  // Security
  SECURITY_REQUEST_BLOCKED: 'SECURITY_REQUEST_BLOCKED',

  // Solana
  SOLANA_WALLET_VERIFICATION_FAILED: 'SOLANA_WALLET_VERIFICATION_FAILED',
});