import React, { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Award, ArrowLeft, Loader2, RefreshCw } from 'lucide-react';
import Container from '../../components/ui/primitives/Container';
import Card from '../../components/common/Card';
import Heading from '../../components/ui/primitives/Heading';
import Text from '../../components/ui/primitives/Text';
import Button from '../../components/common/Button';
import StatCard from '../../components/data-display/StatCard';
import BarChart from '../../components/charts/BarChart';

const ProviderRevenue = function ProviderRevenue() {
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const response = await fetch('/api/executive/revenue/providers', {
        credentials: 'include',
      });
      const payload = await response.json();
      if (response.ok) {
        setData(payload.data);
      }
    } catch (_err) {
      // silent
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const handleBack = useCallback(() => navigate('/executive'), [navigate]);

  return (
    <Container size="xl" className="py-6">
      <Button variant="ghost" size="sm" onClick={handleBack} leadingIcon={ArrowLeft}>
        Back
      </Button>

      <div className="mt-4">
        <div className="flex items-center gap-3">
          <span className="flex h-11 w-11 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600">
            <Award size={20} aria-hidden="true" />
          </span>
          <div>
            <Heading level={1} size="text-2xl">
              Provider Revenue
            </Heading>
            <Text color="muted" className="text-xs">
              Revenue generated by providers and paid to the platform
            </Text>
          </div>
        </div>

        <div className="mt-6 grid grid-cols-2 gap-4 lg:grid-cols-4">
          <StatCard
            label="Total Revenue"
            value={data?.total !== undefined ? `$${data.total}` : '—'}
            icon={Award}
            variant="success"
            loading={loading}
          />
          <StatCard
            label="Platform Share"
            value={data?.platformShare !== undefined ? `$${data.platformShare}` : '—'}
            icon={Award}
            variant="primary"
            loading={loading}
          />
          <StatCard
            label="Provider Payouts"
            value={data?.providerPayouts !== undefined ? `$${data.providerPayouts}` : '—'}
            icon={Award}
            variant="info"
            loading={loading}
          />
          <StatCard
            label="Active Providers"
            value={data?.activeProviders || 0}
            icon={Award}
            variant="default"
            loading={loading}
          />
        </div>

        {data?.topProviders && data.topProviders.length > 0 ? (
          <Card padding="lg" className="mt-6">
            <Heading level={3} size="text-base">
              Top Providers by Revenue
            </Heading>
            <div className="mt-4">
              <BarChart
                data={data.topProviders}
                bars={[{ dataKey: 'revenue', name: 'Revenue', color: '#4f46e5' }]}
                xKey="name"
                height={300}
                horizontal
                tooltipFormatter={(value) => `$${Number(value).toLocaleString()}`}
              />
            </div>
          </Card>
        ) : null}
      </div>
    </Container>
  );
};

export default ProviderRevenue;